export const districts = [

    { "id": 21, "name": "ঢাকা", "en_name": "Dhaka" },
    { "id": 11, "name": "চট্টগ্রাম", "en_name": "Chattogram" },
    { "id": 1, "name": "কক্সবাজার", "en_name": "Cox's Bazar" },
    { "id": 2, "name": "কিশোরগঞ্জ", "en_name": "Kishoreganj" },
    { "id": 3, "name": "কুমিল্লা", "en_name": "Cumilla" },
    { "id": 4, "name": "কুষ্টিয়া", "en_name": "Kushtia" },
    { "id": 5, "name": "কুড়িগ্রাম", "en_name": "Kurigram" },
    { "id": 6, "name": "খাগড়াছড়ি", "en_name": "Khagrachhari" },
    { "id": 7, "name": "খুলনা", "en_name": "Khulna" },
    { "id": 8, "name": "গাইবান্ধা", "en_name": "Gaibandha" },
    { "id": 9, "name": "গাজীপুর", "en_name": "Gazipur" },
    { "id": 10, "name": "গোপালগঞ্জ", "en_name": "Gopalganj" },
    { "id": 12, "name": "চাঁদপুর", "en_name": "Chandpur" },
    { "id": 13, "name": "চাঁপাইনবাবগঞ্জ", "en_name": "Chapainawabganj" },
    { "id": 14, "name": "চুয়াডাঙ্গা", "en_name": "Chuadanga" },
    { "id": 15, "name": "জামালপুর", "en_name": "Jamalpur" },
    { "id": 16, "name": "জয়পুরহাট", "en_name": "Joypurhat" },
    { "id": 17, "name": "ঝালকাঠি", "en_name": "Jhalokati" },
    { "id": 18, "name": "ঝিনাইদহ", "en_name": "Jhenaidah" },
    { "id": 19, "name": "টাঙ্গাইল", "en_name": "Tangail" },
    { "id": 20, "name": "ঠাকুরগাঁও", "en_name": "Thakurgaon" },
    { "id": 22, "name": "দিনাজপুর", "en_name": "Dinajpur" },
    { "id": 23, "name": "নওগাঁ", "en_name": "Naogaon" },
    { "id": 24, "name": "নরসিংদী", "en_name": "Narsingdi" },
    { "id": 25, "name": "নাটোর", "en_name": "Natore" },
    { "id": 26, "name": "নারায়ণগঞ্জ", "en_name": "Narayanganj" },
    { "id": 27, "name": "নীলফামারী", "en_name": "Nilphamari" },
    { "id": 28, "name": "নেত্রকোনা", "en_name": "Netrokona" },
    { "id": 29, "name": "নোয়াখালী", "en_name": "Noakhali" },
    { "id": 30, "name": "নড়াইল", "en_name": "Narail" },
    { "id": 31, "name": "পঞ্চগড়", "en_name": "Panchagarh" },
    { "id": 32, "name": "পটুয়াখালী", "en_name": "Patuakhali" },
    { "id": 33, "name": "পাবনা", "en_name": "Pabna" },
    { "id": 34, "name": "পিরোজপুর", "en_name": "Pirojpur" },
    { "id": 35, "name": "ফরিদপুর", "en_name": "Faridpur" },
    { "id": 36, "name": "ফেনী", "en_name": "Feni" },
    { "id": 37, "name": "বগুড়া", "en_name": "Bogra" },
    { "id": 38, "name": "বরগুনা", "en_name": "Barguna" },
    { "id": 39, "name": "বরিশাল", "en_name": "Barishal" },
    { "id": 40, "name": "বাগেরহাট", "en_name": "Bagerhat" },
    { "id": 41, "name": "বান্দরবান", "en_name": "Bandarban" },
    { "id": 42, "name": "ব্রাহ্মণবাড়িয়া", "en_name": "Brahmanbaria" },
    { "id": 43, "name": "ভোলা", "en_name": "Bhola" },
    { "id": 44, "name": "মাগুরা", "en_name": "Magura" },
    { "id": 45, "name": "মাদারীপুর", "en_name": "Madaripur" },
    { "id": 46, "name": "মানিকগঞ্জ", "en_name": "Manikganj" },
    { "id": 47, "name": "মুন্সিগঞ্জ", "en_name": "Munshiganj" },
    { "id": 48, "name": "মেহেরপুর", "en_name": "Meherpur" },
    { "id": 49, "name": "মৌলভীবাজার", "en_name": "Moulvibazar" },
    { "id": 50, "name": "ময়মনসিংহ", "en_name": "Mymensingh" },
    { "id": 51, "name": "যশোর", "en_name": "Jashore" },
    { "id": 52, "name": "রংপুর", "en_name": "Rangpur" },
    { "id": 53, "name": "রাঙামাটি", "en_name": "Rangamati" },
    { "id": 54, "name": "রাজবাড়ী", "en_name": "Rajbari" },
    { "id": 55, "name": "রাজশাহী", "en_name": "Rajshahi" },
    { "id": 56, "name": "লক্ষ্মীপুর", "en_name": "Lakshmipur" },
    { "id": 57, "name": "লালমনিরহাট", "en_name": "Lalmonirhat" },
    { "id": 58, "name": "শরীয়তপুর", "en_name": "Shariatpur" },
    { "id": 59, "name": "শেরপুর", "en_name": "Sherpur" },
    { "id": 60, "name": "সাতক্ষীরা", "en_name": "Satkhira" },
    { "id": 61, "name": "সিরাজগঞ্জ", "en_name": "Sirajganj" },
    { "id": 62, "name": "সিলেট", "en_name": "Sylhet" },
    { "id": 63, "name": "সুনামগঞ্জ", "en_name": "Sunamganj" },
    { "id": 64, "name": "হবিগঞ্জ", "en_name": "Habiganj" }
  ]
  

  export const upazilas: { [key: number]: string[] } = {
    1: ["কক্সবাজার সদর", "উখিয়া", "টেকনাফ", "রামু", "চকরিয়া", "মহেশখালী", "পেকুয়া", "কুতুবদিয়া", "ঈদগাঁও"],
    2: ["কিশোরগঞ্জ সদর", "করিমগঞ্জ", "তাড়াইল", "হোসেনপুর", "কটিয়াদী", "কুলিয়ারচর", "ভৈরব", "নিকলী", "বাজিতপুর", "ইটনা", "মিঠামইন", "অষ্টগ্রাম", "পাকুন্দিয়া"],
    3: ["কুমিল্লা সদর", "লাকসাম", "দেবিদ্বার", "মুরাদনগর", "দাউদকান্দি", "চৌদ্দগ্রাম", "বরুড়া", "বুড়িচং", "ব্রাহ্মণপাড়া", "চাঁন্দিনা", "হোমনা", "লাঙ্গলকোট", "মেঘনা", "মনোহরগঞ্জ", "তিতাস", "সদর দক্ষিণ"],
    4: ["কুষ্টিয়া সদর", "কুমারখালী", "খোকসা", "মিরপুর", "দৌলতপুর", "ভেড়ামারা"],
    5: ["কুড়িগ্রাম সদর", "উলিপুর", "চিলমারী", "রুমারী", "চর রাজিবপুর", "নাগেশ্বরী", "ভুরুঙ্গামারী", "রাজারহাট", " কুড়িগ্রাম ফুলবাড়ী"],
    6: ["খাগড়াছড়ি সদর", "দিঘীনালা", "পানছড়ি", "মাটিরাঙ্গা", "মহালছড়ি", "মানিকছড়ি", "রামগড়", "লক্ষ্মীছড়ি", "গুইমারা"],
    7: ["খুলনা সদর", "কয়রা", "ডুমুরিয়া", "তেরখাদা", "দাকোপ", "দিঘলিয়া", "পাইকগাছা", "ফুলতলা", "বটিয়াঘাটা", "রূপসা"],
    8: ["গাইবান্ধা সদর", "সাদুল্লাপুর", "পলাশবাড়ী", "সুন্দরগঞ্জ", "সাঘাটা", "গোবিন্দগঞ্জ", "ফুলছড়ি"],
    9: ["গাজীপুর সদর", "কালিয়াকৈর", "কালীগঞ্জ", "কপাসিয়া", "শ্রীপুর"],
    10: ["গোপালগঞ্জ সদর", "কোটালীপাড়া", "টুঙ্গিপাড়া", "কাশিয়ানী", "مুকসুদপুর"],
    11: ["চট্টগ্রাম সিটি", "আনোয়ারা উপজেলা সদর", "বাঁশখালী... উপজেলা সদর", "বোয়ালখালী উপজেলা সদর", "চন্দনাইশ... উপজেলা সদর", "ফটিকছড়ি উপজেলা সদর", "হাটহাজারী উপজেলা সদর", "লোহাগাড়া উপজেলা সদর (সিটিজি)", "মীরসরাই", "পটিয়া উপজেলা সদর", 
  "রাঙ্গুনিয়া উপজেলা সদর", "রাউজান উপজেলা সদর", "সাতকানিয়া উপজেলা সদর", "সীতাকুণ্ড", "কর্নেল হাট (চট্টগ্রাম)", "পতেঙ্গা চট্টগ্রাম", "চট্টগ্রাম প্রকৌশল ও প্রযুক্তি বিশ্ববিদ্যালয় (চুয়েট)", "অক্সিজেন মোড়", "হালিশহর", "এ কে খান", 
  "পাহাড়তলী", "আকবর শাহ", "চট্টগ্রাম ইপিজেড", "আগ্রাবাদ", "চট্টগ্রাম নিউ মার্কেট", "আন্দরকিল্লা", "চকবাজার", "সদরঘাট", "জিইসি মোড়", "খুলশী", 
  "২ নম্বর গেট", "পাচঁলাইশ", "বায়েজিদ বোস্তামী", "নয়াবাজার", "কদমতলী", "দেওয়ানহাট", "সাগরিকা", "অলঙ্কার", "ফয়েজ লেক", "মুরাদপুর", 
  "আতুরের ডিপো", "বাকলিয়া", "মির্জারপুল", "বহদ্দারহাট", "মাদারবাড়ী", "শেখ মুজিব রোড", "চৌমুহনী", "ডবলমুরিং", "আছাদগঞ্জ", "খাতুনগঞ্জ", 
  "হাটহাজারী", "চান্দগাঁও", "কোতোয়ালী", "রাউজান", "সাতকানিয়া", "আনোয়ারা", "বাঁশখালী", "কর্ণফুলী", "বোয়ালখালী", "চন্দনাইশ", 
  "পটিয়া", "চট্টগ্রাম বন্দর", "পতেঙ্গা", "বায়েজিদ বোস্তামী", "বাকলিয়া", "ভুজপুর", "চৌধুরী হাট", "রাঙ্গুনিয়া", "সীতাকুণ্ড", "ফটিকছড়ি", 
  "মীরসরাই", "সন্দ্বীপ", "লালখান বাজার", "গরীবুল্লাহ শাহ মাজার", "দামপাড়া", "জনতা কলোনি", "মনসুরাবাদ", "ঝাউতলা", "নাসিরাবাদ", "সুগন্ধা আবাসিক এলাকা", 
  "ষোলশহর", "রোজ ভ্যালি আবাসিক এলাকা", "অক্সিজেন", "চট্টগ্রাম সেনানিবাস", "মেহেদীবাগ", "কাজীর দেউড়ী", "জামালখান", "ইপিজেড", "ফিরিঙ্গী বাজার", "পাথরঘাটা", 
  "পারৈকোড়া", "আল-আমিন বারীয়া মাদ্রাসা", "গাছবাড়িয়া", "পূর্ব জোয়ারা", "বারমা", "দোহাজারী", "রামগড় হেড অফিস", "হারুয়ালছড়ি", "নাজিরহাট", "জারাছড়ি", 
  "কালীপুর", "গোরাকঘাট", "লংগদু", "মারিশ্যা", "বরকল", "পদুয়া", "আনন্দবাজার", "জগন্নাথ হাট", "বি.আই.টি পোস্ট অফিস", "ফতেপুর", 
  "বীনাজুরী", "গহিরা", "কুণ্ডেশ্বরী", "মহামুনি", "দেওয়ানপুর", "রামপুরা", "চট্টগ্রাম পলিটেকনিক ইনস্টিটিউট", "মধ্য পতেঙ্গা", "জলদিয়া মেরিন একাডেমি", "উত্তর কাট্টলী", 
  "চট্টগ্রাম সেলার্স কলোনি", "চট্টগ্রাম বিমানবন্দর", "উত্তর হালিশহর", "খান বাহাদুর", "গুনাগরী", "বাণীগ্রাম", "ইউনুস নগর", "ফতেয়াবাদ", "গড়দুয়ারা", "কাটিরহাট", 
  "মাদ্রাসা", "নূরালীবাড়ী", "রাজস্থলী", "কানুনগোপাড়া", "সারোয়াতলী", "ইকবাল পার্ক", "বাইতুল ইজ্জত", "বেতবুনিয়া", "কালামপাতি", "নানিয়ারচর", 
  "ওয়াজেদিয়া", "বালুচরা", "রাণীরহাট"],
    12: ["চাঁদপুর সদর", "হাজীগঞ্জ", "কচুয়া", "ফরিদগঞ্জ", "মতলব উত্তর", "মতলব দক্ষিণ", "হাইমচর", "শাহরাস্তি"],
    13: ["চাঁপাইনবাবগঞ্জ সদর", "শিবগঞ্জ", "গোমস্তাপুর", "নাচোল", "ভোলাহাট"],
    14: ["চুয়াডাঙ্গা সদর", "আলমডাঙ্গা", "দামুড়হুদা", "জীবননগর"],
    15: ["জামালপুর সদর", "মেলান্দহ", "ইসলামপুর", "দেওয়ানগঞ্জ", "সরিষাবাড়ী", "মাদারগঞ্জ", "বকশীগঞ্জ"],
    16: ["জয়পুরহাট সদর", "পাঁচবিবি", "আক্কেলপুর", "কালাই", "ক্ষেতলাল"],
    17: ["ঝালকাঠি সদর", "নলছিটি", "রাজাপুর", "কাঠালিয়া"],
    18: ["ঝিনাইদহ সদর", "শৈলকুপা", "হরিণাকুণ্ডু", "কালীগঞ্জ", "কোটচাঁদপুর", "মহেশপুর"],
    19: ["টাঙ্গাইল সদর", "কালিহাতী", "ঘাটাইল", "বাসাইল", "গোপালপুর", "মির্জাপুর", "নাগরপুর", "مধুপুর", "সখিপুর", "দেলদুয়ার", "ধনবাড়ী", "ভূঞাপুর"],
    20: ["ঠাকুরগাঁও সদর", "পীরগঞ্জ", "বালীয়াডাঙ্গী", "রাণীশংকৈল", "হরিপুর"],
    
    21: ["সাভার", "আশুলিয়া", "হেমায়েতপুর", "নবীনগর", "ধামরাই", "কেরানীগঞ্জ", "কদমতলী (কেরানীগঞ্জ)", "জিঞ্জিরা", "নবাবগঞ্জ", "দোহার", 
  "মিরপুর-১", "মিরপুর-২", "মিরপুর-১০", "মিরপুর-১১", "মিরপুর-১২", "মিরপুর-১৩", "মিরপুর-১৪", "মিরপুর ডিওএইচএস (DOHS)", "মিরপুর-৬০ ফিট", "শেওড়াপাড়া", 
  "কাজীপাড়া", "পল্লবী", "রূপনগর", "শাহ আলী", "কাফরুল", "আগারগাঁও", "তালতলা", "উত্তরা সেক্টর-১ থেকে ১০", "উত্তরা সেক্টর-১১ থেকে ১৮", "উত্তরা মডেল টাউন", 
  "দিয়াবাড়ী", "আব্দুল্লাহপুর", "উত্তরাখান", "দক্ষিণখান", "ফায়দাবাদ", "বিমানবন্দর এলাকা", "খিলক্ষেত", "নিকুঞ্জ-১", "নিকুঞ্জ-২", "কুড়িল", 
  "কুড়াতলী", "জোয়ার সাহারা", "বসুন্ধরা আবাসিক এলাকা", "বারিধারা আবাসিক এলাকা", "বারিধারা ডিওএইচএস (DOHS)", "নদ্দা", "কালাচাঁদপুর", "গুলশান-১", "গুলশান-২", "বনানী", 
  "বনানী ডিওএইচএস (DOHS)", "মহাখালী", "মহাখালী ডিওএইচএস (DOHS)", "নিকেতন", "তেজগাঁও", "তেজগাঁও শিল্প এলাকা", "কারওয়ান বাজার", "ফার্মগেট", "রাজাবাজার", "ইন্দিরা রোড", 
  "ধানমন্ডি", "কলাবাগান", "কাঠালবাগান", "গ্রিন রোড", "সেন্ট্রাল রোড", "মোহাম্মদপুর", "জাপান গার্ডেন সিটি", "শিয়া মসজিদ", "আদাবর", "শেখেরটেক", 
  "ঢাকা উদ্যান", "বছিলা", "হাজারীবাগ", "জিগাতলা", "লালমাটিয়া", "রায়েরবাজার", "লালবাগ", "চকবাজার", "ইসলামপুর", "কোতোয়ালী", 
  "বাবু বাজার", "নবাবপুর", "সদরঘাট", "নবাবপুর", "গেন্ডারিয়া", "ওয়ারী", "টিপু সুলতান রোড", "যাত্রাবাড়ী", "ধলপুর", "শনির আখড়া", 
  "রায়েরবাগ", "মাতুয়াইল", "দনিয়া", "ডেমরা", "শ্যামপুর", "কদমতলী", "সবুজবাগ", "বাসাবো", "খিলগাঁও", "সিপাহীবাগ", 
  "গোড়ান", "রামপুরা", "বনশ্রী", "আফতাবনগর", "মালিবাগ", "মৌচাক", "মগবাজার", "সিদ্ধেশ্বরী", "বেইলি রোড", "শান্তিনগর", 
  "কাকরাইল", "পল্টন", "মতিঝিল", "দিলকুশা", "কমলাপুর", "শাহজাহানপুর", "মুগদা", "মান্ডা", "মানিকনগর", "সায়দাবাদ", 
  "রমনা", "শাহবাগ", "ঢাকা বিশ্ববিদ্যালয় এলাকা", "নিউমার্কেট", "আজিমপুর", "নীলক্ষেত", "বকশিবাজার", "সেগুনবাগিচা", "তোপখানা রোড", "হাতিরঝিল", 
  "বাড্ডা", "উত্তর বাড্ডা", "দক্ষিণ বাড্ডা", "মধ্য বাড্ডা", "মেরুল বাড্ডা", "শাহজাদপুর", "ভাটারা", "সাতারকুল", "বেরাইদ", "কামরাঙ্গীরচর", 
  "ভাষানটেক", "মানিকদি", "মাটিকাটা", "ঢাকা সেনানিবাস (Cantonment)", "বারিধারা", "নতুন বাজার", "নদ্দা", "নাখালপাড়া", "পান্থপথ", "শ্যামলী", 
  "এলিফ্যান্ট রোড", "কাওরান বাজার", "আসাদ গেট", "শংকর", "চাঁনখারপুল", "নাজিমুদ্দিন রোড", "স্টাফ কোয়ার্টার", "মুগদাপাড়া", "বংশাল", "গোলাপবাগ", 
  "গোপীবাগ", "টিকাটুলী", "পোস্তগোলা", "জুড়াইন", "মিরপুর ১", "মিরপুর ২", "মিরপুর ৬", "মিরপুর ১১", "মিরপুর ১২", "মিরপুর ১০", 
  "কালশী", "মিরপুর সেনানিবাস", "কল্যাণপুর", "দারুস সালাম", "আজমপুর", "নিকুঞ্জ ১", "উত্তরাখান-দক্ষিণখান", "বারিধারা ব্লক-জে", "শাহজাদপুর পূর্ব", "শিপাহীবাগ", 
  "মেরাদিয়া", "ইস্কাটন", "মনিপুরিপাড়া", "তেজকুনিপাড়া", "ধানমন্ডি ২৭", "ধানমন্ডি ৩২", "গ্রিন রোড ১-৭০", "ধানমন্ডি ১৫", "ভূতের গলি", "ভাষান টেক", 
  "সায়েন্স ল্যাব", "শুক্রাবাদ", "নূরজাহান রোড", "ইকবাল রোড", "বাবর রোড", "তাজমহল রোড", "জাকির হোসেন রোড", "পিসি কালচার হাউজিং", "নবোদয় হাউজিং লিমিটেড", "মোহাম্মদীয়া হাউজিং লিমিটেড", 
  "মিরপুর ৭", "সেনপাড়া", "বাইশ টেকী", "কচুক্ষেত", "ইব্রাহিমপুর", "বালুঘাট", "জনতা হাউজিং", "ইস্টার্ন হাউজিং", "আহমেদবাগ", "টোলারবাগ", 
  "আনসার ক্যাম্প", "গোলারটেক", "মনিপুর", "পীরেরবাগ", "গাবতলী", "মাজার রোড", "উত্তরা সেক্টর ৫", "উত্তরা সেক্টর ৩", "উত্তরা সেক্টর ৭", "উত্তরা সেক্টর ১৪", 
  "উত্তরা সেক্টর ১১", "উত্তরা সেক্টর ১৩", "উত্তরা সেক্টর ১০", "উত্তরা সেক্টর ১২", "উত্তরা সেক্টর ৯", "উত্তরা সেক্টর ১", "উত্তরা জসিমউদ্দীন", "লেক সিটি", "উত্তরা সেক্টর ৪", "উত্তরা সেক্টর ৬", 
  "আশকোনা", "কাজলা", "বিবিরবাগিচা", "নন্দিপাড়া", "ফরিদাবাদ", "গুলিস্তান", "লক্ষ্মীবাজার", "আরামবাগ", "ফকিরাপুল", "মিরবাগ", 
  "হাজীপাড়া", "কাকলী", "শাহীনবাগ", "রাজারবাগ", "ধানমন্ডি ৯এ", "ধানমন্ডি ৯", "ধানমন্ডি ৮এ", "ধানমন্ডি ৮", "ধানমন্ডি ১", "ধানমন্ডি ২", 
  "ধানমন্ডি ১১এ", "ধানমন্ডি ১২এ", "ধানমন্ডি ১০এ", "ধানমন্ডি ১এ", "ধানমন্ডি ২এ", "ধানমন্ডি ৩", "ধানমন্ডি ৪", "ধানমন্ডি ৩এ", "ধানমন্ডি ৪এ", "ধানমন্ডি ৫এ", 
  "ধানমন্ডি ৫", "ধানমন্ডি ৬এ", "ধানমন্ডি ৭", "ধানমন্ডি ৭এ", "উত্তরা ৮", "কেরানীগঞ্জ উপজেলা সদর", "জিঞ্জিরা", "জাজিরা", "আঁটি বাজার", "কলাতিয়া", 
  "দোহর উপজেলা সদর", "নবাবগঞ্জ উপজেলা সদর", "বর্ধন বাড়ী", "জাহাঙ্গীরনগর", "জামগড়া", "পল্লী বিদ্যুৎ", "বাইপাইল", "জিরাবো", "জিরানী", "এনাম মেডিকেল", 
  "পশ্চিম রামপুরা", "নুরেরচালা", "গোপীপাড়া", "৩০০ ফিট", "পশ্চিম পান্থপথ", "কাদেরাবাদ হাউজিং", "চান মিয়া হাউজিং", "সাভার সদর", "সাভার ব্যাংক কলোনি", 
  "মহানগর প্রজেক্ট", "ধানমন্ডি ২৮", "ঢাকা হাউজিং", "রাজিয়া সুলতানা Road", "সলিমুল্লাহ রোড", "শেরশাহ সুরী রোড", "স্যার সৈয়দ রোড", "আসাদ এভিনিউ", "টাউন হল", "কৃষি মার্কেট", 
  "আজিজ মহল্লা", "এফডিসি", "নয়াতোলা", "পেয়ারাবাগ", "পল্লিমা", "আনসার ক্যাম্প (মগবাজার)", "খিলগাঁও তালতলা", "তিলপাপাড়া", "মধুবাগ", "উলন", 
  "যমুনা ফিউচার পার্ক", "আজিজ সরণি", "কোকাকোলা", "অ্যাপোলো হাসপাতাল", "স্বাধীনতা সরণি", "সৈনিক ক্লাব", "বাংলাদেশ বেতার", "সোনি সিনেমা হল", "দক্ষিণ বিশিল", "বাংলা কলেজ", 
  "টেকনিক্যাল", "গাবতলী ঢাকা", "কাওলা", "বিমানবন্দর ঢাকা", "হাজী ক্যাম্প", "কসাই বাড়ী", "মোলার টেক", "প্রেম বাগান", "গাওয়াইর", "বাউনিয়া বাজার", 
  "আজমপুর কাঁচাবাজার", "চালাবন", "রাজলক্ষ্মী", "হাউস বিল্ডিং", "কামারপাড়া", "বাইতুল আমান হাউজিং", "বাঁশবাড়ী", "চাঁদ উদ্যান", "জেনেভা ক্যাম্প", "হুমায়ুন রোড", 
  "আওরঙ্গজেব রোড", "জাফরাবাদ", "কাটাসুর", "মোহাম্মদপুর থানা (নতুন)", "সোবহানবাগ", "টোল্লাবাগ (সোবহানবাগ)", "পশ্চিম রাজাবাজার", "পূর্ব রাজাবাজার", "ক্রিসেন্ট রোড", "নর্থ রোড", 
  "হাতিরপুল", "পরিবাগ", "পিলখানা", "গণকটুলী", "বোরহানপুর", "পলাশী", "বারিধারা ডিপ্লোমেটিক", "টিবি গেট", "রসুলবাগ", "আমতলী", 
  "কড়াইল বস্তি", "মহাখালী ওয়ারলেস", "এলেনবাড়ী", "পশ্চিম নাখালপাড়া", "পূর্ব নাখালপাড়া", "নাভিস্কো", "জাহাঙ্গীর গেট", "আর্জতপাড়া", "Tejgaon পুরাতন বিমানবন্দর", "জোয়ার সাহারা", 
  "বনানী (চেয়ারম্যান বাড়ী)", "প্রেস ক্লাব", "মিন্টু রোড", "শহীদবাগ", "বাসাবো পাটোয়ারী গলি", "মাদারটেক", "মদিনাবাগ", "পটুয়াটুলী", "শামীবাক", "বনগ্রাম", 
  "মালিটোলা", "তাঁতীবাজার", "মিটফোর্ড", "নয়াবাজার", "সিদ্দিকবাজার", "বায়তুল মোকাররম", "জিপিও", "বিজয়নগর", "আগা সাদেক রোড", "উর্দু রোড", 
  "বেগমবাজার", "आरমানিটোলা", "নাজিরাবাজার", "বড় সাহেব বাজার", "জগন্নাথ বিশ্ববিদ্যালয়", "শাঁখারীবাজার", "কোতোয়ালী", "নরিন্দা", "সাভার বাসস্ট্যান্ড", "রেডিও কলোনি", 
  "রাজাশন", "আনন্দপুর", "সাভার বাজার রোড", "নামাবাজার", "ব্যাংক কলোনি", "আড়াপাড়া", "চৌধুরীপাড়া", "বিজয় সরণি", "কার্নিভাল পয়েন্ট (মেট্রো)", "গ্রিন রোড ৭১-১৫০", 
  "টোল্লাবাগ (জিগাতলা)", "কুড়িল চৌরাস্তা", "কুড়িল বিশ্বরোড", "কুড়িল ঘাটপাড়", "জগন্নাথপুর", "সৈয়দ নগর", "সোলমাইদ", "ডালিবাড়ী কাঁচাবাজার", "খিলবাড়ির টেক", "বাঁশতলা", 
  "উত্তরপাড়া", "দক্ষিণপাড়া", "শুভাস্তু নজর ভ্যালি", "পূর্বাচল ৩০০ ফিট", "ডিআইটি প্রজেক্ট", "রামপুরা বাজার", "পূর্ব রামপুরা", "পশ্চিম রামপুরা", "রামপুরা বনশ্রী", "দক্ষিণ বনশ্রী", 
  "বনানী ১", "বনানী ২", "বনানী ৮", "বনানী ১১", "বনানী ১৭", "বনানী ২১", "বনানী ২৩", "কবরস্থান রোড", "মাছরাঙা টেলিভিশন", "নৌবাহিনী সদর দফতর", "আশলতা, বনলতা", "র‌্যাডিসন ওয়াটার ব্লু হোটেল", "কামাল আতাতুর্ক এভিনিউ", "টিএন্ডটি কলোনি", 
  "গুলশান এভিনিউ", "আগোরা", "পুলিশ প্লাজা", "পাকিস্তান দূতাবাস", "ইউনাইটেড হাসপাতাল", "রামপুরা হাজীপাড়া", "মাতুয়াইল", "১২ তলা", "আম বাগান", "আবুজার গিফারী গলি", 
  "আবুল হোটেল", "আদ্-দ্বীন হাসপাতাল", "বিএফডিসি মোড়", "এলেন বারী", "আর্জতপাড়া", "বিএএফ শাহীন কলেজ", "বাগানবাড়ী", "বাটা গলি", "বেগুন বারী", "বেপারী গলি", 
  "বিজি প্রেস", "ভূঁইয়া পাড়া", "বিয়াম অডিটোরিয়াম", "বড় মগবাজার", "সেন্টার পয়েন্ট", "চেয়ারম্যান গলি", "চ্যানেল ২৪", "খ্রিস্টান পাড়া", "সিআইডি অফিস", "স্টাফ কোয়ার্টার", 
  "পূর্ব গোড়ান", "পূর্ব নয়াতোলা", "গ্রিন ওয়ে", "গুলবাগ", "গুলশান আড়ং", "হাজারী বারী", "ইমাম বাগ", "কাজী অফিস গলি", "খিলগাঁও ব্লক এ", "খিলগাঁও ব্লক বি", 
  "খিলগাঁও ব্লক সি", "কুনিপাড়া", "লুকাসের মোড়", "মালিবাগ ১ম লেন", "মালিবাগ চৌধুরীপাড়া", "নিঝুম অফিসার্স কোয়ার্টার", "উত্তর গোড়ান", "নতুন বাগ", "পাগলা মাজার গলি", "প্রধানমন্ত্রীর কার্যালয়", 
  "প্রভাতী বাগ", "র‍্যাংগস ভবন", "রিয়াজ বাগ", "রোমা সেঞ্চুরি", "স্বাধীনতা টাওয়ার", "শান্তিবাগ", "সাতরাস্তা", "সত্তা গলি", "শেরন বাগ", "সোনারগাঁও", 
  "টিএন্ডটি গলি", "তেজগাঁও ট্রাক স্ট্যান্ড", "তিব্বত", "ট্রাক স্ট্যান্ড", "উত্তরা সেন্টার", "ভদ্র গলি", "পশ্চিম মালিবাগ","কুল্লা", 
  "জয়দেবপুর", "চৌহাট", "বাইশাকান্দা", "গাঙ্গুটিয়া", "ভাড়ারিয়া", "বালিয়া", "কুশুরা", "নান্নার", "রোয়াইল", "সানোরা", 
  "সোমভাগ", "সুয়াপুর", "সুতিপাড়া", "সারালিয়া", "বানগ্রাম", "ভাকুর্তা", "বিরুলিয়া", "ধামসোনা", "কাউন্দিয়া", "পাথালিয়া", 
  "আমীনবাজার", "সাভার সেনানিবাস", "শিমুলিয়া", "তেঁতুলঝোড়া", "ইয়ারপুর", "কুশুমহাটি", "মাহমুদপুর", "মুকসুদপুর", "নারিশা", "নয়াবাড়ী", 
  "রায়পাড়া", "সুতারপাড়া", "কাঞ্চন ব্রিজ", "কোনাপাড়া", "পোস্ট অফিস", "ঢাকা সেনানিবাস - পোস্ট অফিস", "তালতলা মোল্লাপাড়া", "পশ্চিম কাফরুল", "ঢাকা বোট ক্লাব", "বিজিএমইএ ইউনিভার্সিটি", 
  "আশুলিয়া বেড়িবাঁধ","ইন্টারন্যাশনাল মেডিকেল কলেজ", "সারদাগঞ্জ", "বাগবাড়ী", "কাশিমপুর", "কামাজুরি", "স্কয়ার", "পলাশবাড়ী", 
  "খেজুর বাগান", "গৌরীপুর বি.বাংলা", "চাড়াবাগ", "খাগান", "আক্রাইন", "কলমা", "আনারকলি", "দুসাইদ", "কাটগড়া", "কুতুরিয়া", 
  "সেরালী মার্কেট", "বিশমাইল", "জাহাঙ্গীরনগর বিশ্ববিদ্যালয়", "অরুণাপল্লী", "ইসলাম নগর", "ফ্যান্টাসি কিংডম এলাকা", "ডিইপিজেড (DEPZ)", "শ্রীপুর", "চক্রবর্তী বেক্সিমকো", "বারইপাড়া", 
  "নন্দনপার্ক", "ধামরাই সদর", "ধামরাই ধুলিভিটা", "ধামরাই আমতলী", "কালামপুর", "বারবাড়িয়া", "বাটুলী", "কাওলিপাড়া", "বীর উত্তম সিআর দত্ত রোড", "কাজী নজরুল ইসলাম এভিনিউ ১-৩০", 
  "কাজী নজরুল ইসলাম এভিনিউ ৩০-১০৭", "কাজী নজরুল ইসলাম এভিনিউ ১০৮ ও ঊর্ধ্বে", "গ্রিন রোড ১৫১ ও ঊর্ধ্বে", "হাসনাবাদ", "বসুন্ধরা ব্লক এম থেকে পি"],

    22: ["দিনাজপুর সদর", "বিরামপুর", "নবাবগঞ্জ", "বীরগঞ্জ", "বোচাগঞ্জ","চিরিরবন্দর", "ফুলবাড়ী", "কাহারোল", "খানসামা", "পার্বতীপুর", "হাকিমপুর", "ঘোড়াঘাট"],
    23: ["নওগাঁ সদর", "পত্নীতলা", "ধামইরহাট", "মহাদেবপুর", "পোরশা", "সাপাহার", "বদলগাছী", "আত্রাই", "রানীনগর", "নিয়ামতপুর", "মান্দা"],
    24: ["নরসিংদী সদর", "পলাশ", "শিবপুর", "মনোহরদী", "বেলাবো", "রায়পুরা"],
    25: ["নাটোর সদর", "বাগাতিপাড়া", "বড়াইগ্রাম", "গুরুদাসপুর", "লালপুর", "সিংড়া", "নলডাঙ্গা"],
    26: ["নারায়ণগঞ্জ সদর", "বন্দর", "আড়াইহাজার", "রূপগঞ্জ", "সোনারগাঁও"],
    27: ["নীলফামারী সদর", "সৈয়দপুর", "জলঢাকা", "কিশোরগঞ্জ", "ডোমার", "ডিমলা"],
    28: ["নেত্রকোনা সদর", "বারহাট্টা", "কলমাকান্দা", "দুর্গাপুর", "কেন্দুয়া", "মদন", "মোহনগঞ্জ", "পূর্বধলা", "খালিয়াজুরী", "আটপাড়া"],
    29: ["নোয়াখালী সদর", "কোম্পানীগঞ্জ", "বেগমগঞ্জ", "চাটখিল", "সেনবাগ", "হাতিয়া", "সুবর্ণচর", "সোনাইমুড়ী", "কবিরহাট"],
    30: ["নড়াইল সদর", "লোহাগড়া", "কালিয়া"],

    31: ["পঞ্চগড় সদর", "তেঁতুলিয়া", "বোদা", "দেবীগঞ্জ", "আটোয়ারী"],
    32: ["পটুয়াখালী সদর", "বাউফল", "গলাচিপা", "দশমিনা", "মির্জাগঞ্জ", "কলাপাড়া", "দুমকি", "রাঙ্গাবালী"],
    33: ["পাবনা সদর", "ঈশ্বরদী", "ভাঙ্গুড়া", "চাটমোহর", "ফরিদপুর", "সুজানগর", "বেড়া", "আটঘরিয়া", "সাথিয়া"],
    34: ["পিরোজপুর সদর", "নাজিরপুর", "নেছারাবাদ", "কাওখালী", "ভাণ্ডারিয়া", "মঠবাড়িয়া", "ইন্দুরকানী"],
    35: ["ফরিদপুর সদর", "আলফাডাঙ্গা", "বোয়ালমারী", "সদরপুর", "নগরকান্দা", "ভাঙ্গা", "চরভদ্রাসন", "মধুখালী", "সালথা"],
    36: ["ফেনী সদর", "ছাগলনাইয়া", "পরশুরাম", "ফুলগাজী", "দাগনভূঁইয়া", "সোনাগাজী"],
    37: ["বগুড়া সদর", "শাজাহানপুর", "শেরপুর", "ধুনট", "নন্দীগ্রাম", "কাহালু", "আদমদিঘী", "দুপচাঁচিয়া", "শিবগঞ্জ", "সোনাতলা", "গাবতলী", "সারিয়াকান্দি"],
    38: ["বরগুনা সদর", "আমতলী", "পাথরঘাটা", "বামনা", "বেতাগী", "তালতলী"],
    39: ["বরিশাল সদর", "বাকেরগঞ্জ", "বাবুগঞ্জ", "উজিরপুর", "বানারীপাড়া", "গৌরনদী", "আগৈলঝারা", "মুলাদী", "হিজলা", "মেহেন্দিগঞ্জ"],
    40: ["বাগেরহাট সদর", "ফকিরহাট", "মোল্লাহাট", "চিতলমারী", "কচুয়া", "রামপাল", "মোংলা", "শরণখোলা", "মোড়েলগঞ্জ"],
    
    41: ["বান্দরবান সদর", "রুমা", "থানচি", "রোয়াংছড়ি", "লামা", "আলীকদম", "নাইক্ষ্যংছড়ি"],
    42: ["ব্রাহ্মণবাড়িয়া সদর", "কসবা", "নাসিরনগর", "সরাইল", "আশুগঞ্জ", "আখাউড়া", "নবীনগর", "বাঞ্ছারামপুর", "বিজয়নগর"],
    43: ["ভোলা সদর", "বোরহানউদ্দিন", "চরফ্যাশন", "লালমোহন", "তজুমদ্দিন", "দৌলতখান", "মনপুরা"],
    44: ["মাগুরা সদর", "মহম্মদপুর", "শালিখা", "শ্রীপুর"],
    45: ["মাদারীপুর সদর", "শিবচর", "কালকিনি", "রাজৈর", "ডাসার"],
    46: ["মানিকগঞ্জ সদর", "সিংগাইর", "ঘিওর", "সাটুরিয়া", "হরিরামপুর", "শিবালয়", "দৌলতপুর"],
    47: ["মুন্সিগঞ্জ সদর", "শ্রীনগর", "সিরাজদিখান", "লৌহজং", "টংগিবাড়ী", "গজারিয়া"],
    48: ["মেহেরপুর সদর", "গাংনী", "মুজিবনগর"],
    49: ["মৌলভীবাজার সদর", "শ্রীমঙ্গল", "রাজনগর", "কুলাউড়া", "বড়লেখা", "কমলগঞ্জ", "জুড়ী"],
    50: ["ময়মনসিংহ সদর", "মুক্তাগাছা", "ফুলবাড়ীয়া", "ত্রিশাল", "ভালুকা", "গফরগাঁও", "ঈশ্বরগঞ্জ", "নান্দাইল", "গৌরীপুর", "ফুলপুর", "ধোবাউড়া", "হালুয়াঘাট", "তারাকান্দা"],
    
    51: ["যশোর সদর", "ঝিকরগাছা", "শার্শা", "চৌগাছা", "কেশবপুর", "মণিরামপুর", "অভয়নগর", "বাঘেরপাড়া"],
    52: ["রংপুর সদর", "মিঠাপুকুর", "পীরগঞ্জ", "পীরগাছা", "কাউনিয়া", "গঙ্গাচড়া", "বদরগঞ্জ", "তপাধন"],
    53: ["রাঙামাটি সদর", "কাপ্তাই", "কাউখালী", "বাঘাইছড়ি", "লংগদু", "নানিয়ারচর", "রাজস্থলী", "জুরাছড়ি", "বরকল", "বিলাইছড়ি"],
    54: ["রাজবাড়ী সদর", "গোয়ালন্দ", "পাংশা", "বালিয়াকান্দি", "কালুখালী"],
    55: ["রাজশাহী সদর", "পবা", "তানোর", "গোদাগাড়ী", "মোহনপুর", "বাগমারা", "দুর্গাপুর", "পুঠিয়া", "চারঘাট", "বাঘা"],
    56: ["লক্ষ্মীপুর সদর", "রায়পুর", "রামগঞ্জ", "রামগতি", "কমলনগর"],
    57: ["লালমনিরহাট সদর", "কালীগঞ্জ", "হাতীবান্ধা", "পাটগ্রাম", "আদিতমারী"],
    58: ["শরীয়তপুর সদর", "ডামুড্যা", "নড়িয়া", "জাজিরা", "ভেদরগঞ্জ", "গোসাইরহাট"],
    59: ["শেরপুর সদর", "নালিতাবাড়ী", "ঝিনাইগাতী", "নকলা", "শ্রীবরদী"],
    60: ["সাতক্ষীরা সদর", "কলারোয়া", "তালা", "আশাশুনি", "শ্যামনগর", "কালীগঞ্জ", "দেবহাটা"],
    61: ["সিরাজগঞ্জ সদর", "বেলকুচি", "চৌহালী", "কামারখন্দ", "কাজীপুর", "রায়গঞ্জ", "শাহজাদপুর", "তাড়াশ", "উল্লাপাড়া"],
    62: ["সিলেট সদর", "বিয়ানীবাজার", "গোলাপগঞ্জ", "ফেঞ্চুগঞ্জ", "বালাগঞ্জ", "বিশ্বনাথ", "কোম্পানীগঞ্জ", "গৌরীপুর", "জৈন্তাপুর", "কানাইঘাট", "জকিগঞ্জ", "দক্ষিণ সুরমা", "ওসমানীনগর"],
    63: ["সুনামগঞ্জ সদর", "ছাতক", "জগন্নাথপুর", "দিরাই", "শাল্লা", "ধর্মপাশা", "তাহিরপুর", "বিশ্বম্ভরপুর", "দোয়ারাবাজার", "জামালগঞ্জ", "মধ্যনগর"],
    64: ["হবিগঞ্জ সদর", "নবীগঞ্জ", "বাহুবল", "আজমিরীগঞ্জ", "বানিয়াচং", "লাখাই", "চুনারুঘাট", "মাধবপুর", "শায়েস্তাগঞ্জ"]    
}

export const upazilasEn: { [key: number]: string[] } = {
  1: ["Cox's Bazar Sadar", "Ukhiya", "Teknaf", "Ramu", "Chakaria", "Moheshkhali", "Pekua", "Kutubdia", "Eidgaon"],
  2: ["Kishoreganj Sadar", "Karimganj", "Tarail", "Hossainpur", "Kotiadi", "Kuliarchar", "Bhairab", "Nikli", "Bajitpur", "Itna", "Mithamain", "Austagram", "Pakundia"],
  3: ["Cumilla Sadar", "Laksam", "Debidwar", "Muradnagar", "Daudkandi", "Chauddagram", "Barura", "Burichang", "Brahmanpara", "Chandina", "Homna", "Langalkot", "Meghna", "Monohargonj", "Titas", "Sadar South"],
  4: ["Kushtia Sadar", "Kumarkhali", "Khoksa", "Mirpur", "Daulatpur", "Bheramara"],
  5: ["Kurigram Sadar", "Ulipur", "Chilmari", "Rhumari", "Char Rajibpur", "Nageshwari", "Bhurungamari", "Rajarhat", "Kurigram Phulbari"],
  6: ["Khagrachhari Sadar", "Dighinala", "Panchhari", "Matiranga", "Mahalchhari", "Manikchhari", "Ramgarh", "Lakshmichhari", "Guimara"],
  7: ["Khulna Sadar", "Koyra", "Dumuria", "Terkhada", "Dacope", "Dighalia", "Paikgacha", "Phultala", "Batiaghata", "Rupsha"],
  8: ["Gaibandha Sadar", "Sadullapur", "Palashbari", "Sundarganj", "Saghata", "Gobindaganj", "Fulchhari"],
  9: ["Gazipur Sadar", "Kaliakair", "Kaliganj", "Kapasia", "Sreepur"],
  10: ["Gopalganj Sadar", "Kotalipara", "Tungipara", "Kashiani", "Muksudpur"],
  11: ["Chittagong City", "Anwara Upazila Sadar", "Banshkhali Upazila Sadar", "Boalkhali Upazila Sadar", "Chandanaish Upazila Sadar", "Fatikchhari Upazila Sadar", "Hathazari Upazila Sadar", "Lohagara Upazila Sadar (CTG)", "Mirsharai", "Patiya Upazila Sadar", 
  "Rangunia Upazila Sadar", "Raozan Upazila Sadar", "Satkania Upazila Sadar", "Sitakund", "Cornel Hat (Chittagong)", "Patenga Chittagong", "Chittagong University of Engineering & Technology (CUET)", "Oxygen Mor", "Halishohor", "AK Khan", 
  "Pahartoli", "Akbor Shah", "Chittagong EPZ", "Agrabad", "Chittagong New Market", "Andarkilla", "Chowkbazar", "Sadarghat", "GEC Mor", "Khulshi", 
  "2 No Gate", "Panchlaish", "Bayzid Bostami", "Noyabazar", "Kodomtoli", "Dewanhat", "Sagorika", "Alonkar", "Foy's Lake", "Muradpur", 
  "Aturar Depot", "Bakoliya", "Mirjarpol", "Boddarhat", "Madarbari", "SK Mujib Road", "Chowmohoni", "Double Mooring", "Asadganj", "Khatunganj", 
  "Hathazari", "Chandgaon", "Kotwali", "Raozan", "Satkania", "Anowara", "Banshkhali", "Karnaphuli", "Boalkhali", "Chandanaish", 
  "Patiya", "Chittagong Port", "Patenga", "Bayejid Bostami", "Bakalia", "Bhujpur", "Chowdhury Hat", "Rangunia", "Sitakunda", "Fatikchhari", 
  "Mirsharai", "Sandwip", "Lalkhan Bazar", "Garibullah Shah Mazar", "Dampara", "Jonota Colony", "Monsurabad", "Jhautola", "Nasirabad", "Shugandha Residential", 
  "Sholoshahor", "Rose Vally R/A", "Oxygen", "CTG Cantonment", "Mehedibag", "Kajir Dewri", "Jamalkhan", "EPZ", "Firingi Bazar", "Pathar Ghata", 
  "Paroikora", "Al-Amin Baria Madrasa", "Gachbaria", "East Joara", "Barma", "Dohazari", "Ramghar Head Office", "Harualchhari", "Najirhat", "Jarachhari", 
  "Kalipur", "Gorakghat", "Longadu", "Marishya", "Barka", "Padua", "Anandabazar", "Jagannath Hat", "B.I.T Post Office", "Fatepur", 
  "Beenajuri", "Gahira", "Kundeshwari", "Mohamuni", "Dewanpur", "Rampura", "Chittagong Polytechnic Inst.", "Middle Patenga", "Jaldia Marine Academy", "North Katuli", 
  "Chittagong Sailors Colony", "Chittagong Airport", "North Halishahar", "Khan Bahadur", "Gunagari", "Banigram", "Yunus Nagar", "Fatahabad", "Gorduara", "Katirhat", 
  "Madrasa", "Nuralibari", "Rajsthali", "Kanungopara", "Saroatoli", "Iqbal Park", "Baitul Ijjat", "Betbunia", "Kalampati", "Nanichhar", 
  "Wajediya", "Baluchora", "Ranirhat"],
  12: ["Chandpur Sadar", "Haziganj", "Kachua", "Faridganj", "Matlab North", "Matlab South", "Haimchar", "Shahrasti"],
  13: ["Chapainawabganj Sadar", "Shibganj", "Gomastapur", "Nachole", "Volahat"],
  14: ["Chuadanga Sadar", "Alamdanga", "Damurhuda", "Jibannagar"],
  15: ["Jamalpur Sadar", "Melandah", "Islampur", "Dewanganj", "Sarishabari", "Madarganj", "Bakshiganj"],
  16: ["Joypurhat Sadar", "Panchbibi", "Akkelpur", "Kalai", "Khetlal"],
  17: ["Jhalokati Sadar", "Nalchity", "Rajapur", "Kathalia"],
  18: ["Jhenaidah Sadar", "Shailkupa", "Harinakundu", "Kaliganj", "Kotchandpur", "Moheshpur"],
  19: ["Tangail Sadar", "Kalihati", "Ghatail", "Basail", "Gopalpur", "Mirzapur", "Nagarpur", "Madhupur", "Sakhipur", "Delduar", "Dhanbari", "Bhuapur"],
  20: ["Thakurgaon Sadar", "Pirganj", "Baliadangi", "Ranisankail", "Haripur"],
  
  21: ["Savar", "Ashulia", "Hemayetpur", "Nabinagar", "Dhamrai", "Keraniganj", "Kodomtoli (Keraniganj)", "Zinzira", "Nawabganj", "Dohar", 
  "Mirpur 1", "Mirpur 2", "Mirpur 10", "Mirpur 11", "Mirpur 12", "Mirpur 13", "Mirpur 14", "Mirpur DOHS", "Mirpur 60 Feet", "Shewrapara", 
  "Kazipara", "Pallabi", "Rupnagar", "Shah Ali", "Kafrul", "Agargaon", "Taltola", "Uttara Sector 1 to 10", "Uttara Sector 11 to 18", "Uttara Model Town", 
  "Diabari", "Abdullahpur", "Uttar Khan", "Dakkhin Khan", "Faydabad", "Airport Area", "Khilket", "Nikunjo 1", "Nikunjo 2", "Kuril", 
  "Kuratoli", "Joar Sahara", "Bashundhara RA", "Baridhara RA", "Baridhara DOHS", "Norda", "Kalachandpur", "Gulshan 1", "Gulshan 2", "Banani", 
  "Banani DOHS", "Mohakhali", "Mohakhali DOHS", "Niketon", "Tejgaon", "Tejgaon Industrial Area", "Kawran Bazar", "Farmgate", "Rajabazar", "Indira Road", 
  "Dhanmondi", "Kalabagan", "Kathalbagan", "Green Road", "Central Road", "Mohammadpur", "Japan Garden City", "Shia Masjid", "Adabor", "Shekertek", 
  "Dhaka Uddan", "Bosila", "Hazaribagh", "Zigatola", "Lalmatia", "Rayerbazar", "Lalbagh", "Chawkbazar", "Islampur", "Kotwali", 
  "Babu Bazar", "Nawabpur", "Sodorghat", "Sutrapur", "Gendaria", "Wari", "Tipu Sultan Road", "Jatrabari", "Dholpur", "Shonir Akhra", 
  "Rayerbagh", "Matuail", "Donia", "Demra", "Shyampur", "Kodomtoli", "Sabujbagh", "Bashabo", "Khilgaon", "Shipahibag", 
  "Goran", "Rampura", "Banasree", "Aftabnagar", "Malibagh", "Mouchak", "Moghbazar", "Siddheswari", "Bailey Road", "Shantinagar", 
  "Kakrail", "Paltan", "Motijheel", "Dilkusha", "Komlapur", "Shahjahanpur", "Mugda", "Manda", "Maniknagar", "Sayedabad", 
  "Romna", "Shahbagh", "Dhaka University Area", "New Market", "Azimpur", "Nilkhet", "Bakshibazar", "Segunbagicha", "Topkhana Road", "Hatirjheel", 
  "Badda", "Uttar Badda", "Dakkhin Badda", "Modhya Badda", "Merul Badda", "Shahjadpur", "Vatara", "Satarkul", "Beraid", "Kamrangirchor", 
  "Vasantek", "Manikdi", "Matikata", "Dhaka Cantonment", "Baridhara", "Notun Bazar", "Nakhalpara", "Panthapath", "Shyamoli", "Elephant Road", 
  "Asad Gate", "Shankar", "Chankharpul", "Nazimuddin Road", "Staff Quarter", "Mugdapara", "Bangshal", "Golapbagh", "Gopibagh", "Tikatuli", 
  "Postogola", "Jurain", "Mirpur 6", "Kalshi", "Kallayanpur", "Darus Salam", "Azampur", "Uttar Khan - Dakkhin Khan", "Baridhara Block J", "Shahjadpur East", 
  "Meradia", "Eskaton", "Monipuripara", "Tejkunipara", "Dhanmondi 27", "Dhanmondi 32", "Green Road 1-70", "Dhanmondi 15", "Vootergoli", "Science Lab", 
  "Sukrabad", "Nurjahan Road", "Iqbal Road", "Babar Road", "Tajmahal Road", "Jakir Hussain Road", "PC Culture Housing", "Nobodoy Housing Ltd", "Mohammadia Housing Ltd", "Senpara", 
  "Bais Teki", "Kochukhet", "Ibrahimpur", "Balughat", "Janata Housing", "Eastern Housing", "Ahamedbag", "Tolarbag", "Ansar Camp", "Golarteak", 
  "Monipur", "Pirerbag", "Gabtoli", "Mazar Road", "Uttara Sector 5", "Uttara Sector 3", "Uttara Sector 7", "Uttara Sector 14", "Uttara Sector 11", "Uttara Sector 13", 
  "Uttara Sector 10", "Uttara Sector 12", "Uttara Sector 9", "Uttara Sector 1", "Uttara Jasimuddin", "Lake City", "Uttara Sector 4", "Uttara Sector 6", "Ashkona", "Kajla", 
  "Bibirbagicha", "Nondipara", "Foridabad", "Gulistan", "Lakshmibazar", "Arambag", "Fokirapool", "Mirbag", "Hazipara", "Kakoli", 
  "Shaheenbag", "Rajarbag", "Dhanmondi 9A", "Dhanmondi 9", "Dhanmondi 8A", "Dhanmondi 8", "Dhanmondi 1", "Dhanmondi 2", "Dhanmondi 11A", "Dhanmondi 12A", 
  "Dhanmondi 10A", "Dhanmondi 1A", "Dhanmondi 2A", "Dhanmondi 3", "Dhanmondi 4", "Dhanmondi 3A", "Dhanmondi 4A", "Dhanmondi 5A", "Dhanmondi 5", "Dhanmondi 6A", 
  "Dhanmondi 7", "Dhanmondi 7A", "Uttara 8", "Keraniganj Upazila Sadar", "Zazira", "Ati Bazar", "Kalatiya", "Dohar Upazila Sadar", "Nawabganj Upazila Sadar", "Bordhon Bari", 
  "Jahangirnagar", "Jamgora", "Polli Biddyut", "Baipail", "Zirabo", "Jirani", "Enam Medical", "West Rampura", "Nurerchala", "Gopipara", 
  "300ft", "West Panthapath", "Kaderabad Housing", "Chan Mia Housing", "Savar Sadar", "Savar Bank Colony", "Mohanogor Project", "Dhanmondi 28", "Dhaka Housing", "Razia Sultana Road", 
  "Solimullah Road", "Shersah Suri Road", "Sir Syed Road", "Asad Avenue", "Town Hall", "Krishi Market", "Aziz Mohollah", "FDC", "Noyatola", "Peyarabag", 
  "Pollima", "Ansar Camp (Moghbazar)", "Khilgaon Taltola", "Tilpa Para", "Modhubag", "Ulon", "Jamuna Future Park", "Aziz Sarani", "Coca-cola", "Apollo Hospital", 
  "Shadinota Shoroni", "Shoinik Club", "Bangladesh Betar", "SONY Cinema Hall", "South Bishil", "Bangla College", "Technical", "Gabtoli Dhaka", "Kawla", "Airport Dhaka", 
  "Haji Camp", "Koshai Bari", "Mollar Tek", "Prem Bagan", "Gawair", "Baunia Bazar", "Azampur Kacha Bazar", "Chalabon", "Rajlakhsmi", "House Building", 
  "Kamarpara", "Baitul Aman Housing", "Bashbari", "Chand Uddan", "Geneva Camp", "Humayun Road", "Aurongojeb Road", "Jafrabad", "Katasur", "Mohammadpur Thana (New)", 
  "Modhu Bazar", "Dhanmondi 10", "Dhanmondi 11", "Dhanmondi 12", "Dhanmondi 31", "Dhanmondi 13", "Dhanmondi 30", "Dhanmondi 16", "Dhanmondi 13A", "Dhanmondi 14A", 
  "Dahnmondi 15A", "Khamar Bari", "Manik Mia Avenue", "Sobhanbag", "Tallabag (Sobhanbagh)", "West Razabazar", "East Razabazar", "Cresent Road", "North Road", "Hatirpool", 
  "Paribag", "Pilkhana", "Gonok Tuli", "Borhanpur", "Polashi", "Baridhara Diplomatic", "TB Gate", "Rasulbag", "Amtoli", "Korail Bosti", 
  "Mohakhali Wireless", "Elenbari", "West Nakhalpara", "East Nakhalpara", "Nabisco", "Jahangir Gate", "Arjatpara", "Tejgaon Old Airport", "Joarsahara", "Banani (Chairman Bari)", 
  "Press Club", "Mintu Road", "Shahidbag", "Basabo Patwary Goli", "Mather Tek", "Madinabag", "Patuatuli", "Shammibag", "Bonogram", "Manitola", 
  "Tatibazar", "Mitford", "Nayabazar", "Siddiqbazar", "Baytul Mokarrom", "GPO", "Bijay Nagar", "Aga Sadiq Road", "Urdu Road", "Begumbazar", 
  "Armanitola", "Nazirabazar", "Boro Shahebr Bazar", "Jagannath University", "Shakharibazar", "Qatwali", "Narinda", "Savar Bus Stand", "Radio Collony", "Rajashon", 
  "Anondopur", "Savar Bazar Road", "Namabazar", "Bank Collony", "Arapara", "Chowdhury Para", "Bijoy Sarani", "Carnival Point (Metro)", "Green Road 71-150", "Tallabag (Zigatola)", 
  "Kuril Chaurasta", "Kuril Bisso Road", "Kuril Ghatpar", "Jagonnath Pur", "Sayed Nagor", "Soilmaid", "Dalibari Kachabazar", "Khilbarir Take", "Bashtola", "Uttorpara", 
  "Dokkhin Para", "Shubastu Najor Velly", "Purbachal 300 Feet", "DIT Project", "Rampura Bazar", "East Rumpura", "West Rumpura", "Rampura Banassre", "South Banassre", "Banani 1", 
  "Banani 2", "Banani 8", "Banani 11", "Banani 17", "Banani 21", "Banani 23", "Graveyard Road", "Maasranga Television", "Navy Headquarters", "Ashalota, Bonolota", 
  "Radisson Blu Water Hotel", "Kemal Ataturk Avenue", "T&T Colony", "Gulshan Avenue", "Agora", "Police Plaza", "Pakistan Embassy", "United Hospital", "Rampura Hazipara", "12 Tala", 
  "Aam Bagan", "Abujar Bafari Gali", "Abul Hotel", "Addin Hospital", "BFDC Mor", "BAF Shaheen College", "Baganbari", "Bata Gali", "Begun Bari", "Bepari Gali", 
  "BG Press", "Bhauya Para", "Biam Auditorium", "Boro Moghbazar", "Center Point", "Chairman Gali", "Channel 24", "Christian Para", "CID Office", "DNC Staff Quarter", 
  "East Goran", "East Noyatola", "Green Way", "Gulbag", "Gulshan Arong", "Hazari Bari", "Imam Bag", "Kazi Office R Gali", "Khilgaon Block A", "Khilgaon Block B", 
  "Khilgaon Block C", "Kuni Para", "Lukaser Mor", "Mailbag 1st Line", "Malibag Chowdhuripara", "Nijhum Officers Quarters", "North Goran", "Notun Bag", "Paglamajar Gali", "Prime Minister Office", 
  "Provati Bag", "Rangs Vaban", "Riaz Bag", "Roma Century", "Sadhinata Tower", "Santibag", "Satrasta", "Satta Gli", "Sheron Bag", "Shonargoan", 
  "T&T Gali", "Tejgaon Truck Stand", "Tibet", "Truck Stand", "Uttara Center", "Vodro Gali", "West Mailbag", "Warehouse", "Fulfillment", "Kulla", 
  "Jadobpur", "Chauhat", "Baisakanda", "Gangutia", "Bhararia", "Balia", "Kushura", "Nannar", "Rowail", "Sanora", 
  "Sombhag", "Suapur", "Suti Para", "Saralia", "Banagram", "Bhakurta", "Biralia", "Dhamsana", "Kaundia", "Pathalia", 
  "Amin Bazar", "Savar Cantonment", "Shimulia", "Tetuljhora", "Yearpur", "Kushumhati", "Mahmudpur", "Muksudpur", "Narisha", "Nayabari", 
  "Roypara", "Sutar Para", "Kanchan Bridge", "Konapara", "Post Office", "Dhaka Cantonment - Post Office", "Taltola Mollapara", "West Kafrul", "Dhaka Boat Club", "BGMEA University", 
  "Ashulia Beribadh", "Berulia", "Gusulia", "International Medical College", "Sardagonj", "Bagbari", "Kashempur", "Kamajuri", "Square", "Polashbari", 
  "Khejur Bagan", "Gouripur B.Bangla", "Charabad", "Khagan", "Akrain", "Kolma", "Anarkoli", "Dusaid", "Katgora", "Kuturia", 
  "Sherali Market", "Bishmail", "Jahangirnagar University", "Arunapolli", "Islam Nagar", "Fantasy Kingdom Area", "DEPZ", "Sreepur", "Chokroborti Beximco", "Baraipara", 
  "Nandan Park", "Dhamrai Sadar", "Dhamrai Dhulitvita", "Dhamrai Ammtola", "Kalampur", "Barobaria", "Batuli", "Kawlipara", "Bir Uttam CR Datta Road", "Kazi Nazrul Islam Avenue 1-30", 
  "Kazi Nazrul Islam Avenue 30-107", "Kazi Nazrul Islam Avenue 108 & Above", "Green Road 151 & Above", "Hasnabad", "Bashundhara Block M to P"],

  22: ["Dinajpur Sadar", "Birampur", "Nawabganj", "Birganj", "Bochaganj", "Chirirbandar", "Phulbari", "Kaharole", "Khansama", "Parbatipur", "Hakimpur", "Ghoraghat"],
  23: ["Naogaon Sadar", "Patnitala", "Dhamoirhat", "Mahadebpur", "Porsha", "Sapahar", "Badalgachhi", "Atrai", "Raninagar", "Niamatpur", "Manda"],
  24: ["Narsingdi Sadar", "Palash", "Shibpur", "Monohardi", "Belabo", "Raipura"],
  25: ["Natore Sadar", "Bagatipara", "Baraigram", "Gurudaspur", "Lalpur", "Singra", "Naldanga"],
  26: ["Narayanganj Sadar", "Bandar", "Araihazar", "Rupganj", "Sonargaon"],
  27: ["Nilphamari Sadar", "Sayedpur", "Jaldhaka", "Kishoreganj", "Domar", "Dimla"],
  28: ["Netrokona Sadar", "Barhatta", "Kalamakanda", "Durgapur", "Kendua", "Madan", "Mohanganj", "Purbadhala", "Khaliajuri", "Atpara"],
  29: ["Noakhali Sadar", "Companiganj", "Begumganj", "Chatkhil", "Senbagh", "Hatiya", "Subarnachar", "Sonaimuri", "Kabirhat"],
  30: ["Narail Sadar", "Lohagara", "Kalia"],

  31: ["Panchagarh Sadar", "Tetulia", "Boda", "Debiganj", "Atwari"],
  32: ["Patuakhali Sadar", "Bauphal", "Galachipa", "Dashmina", "Mirzaganj", "Kalapara", "Dumki", "Rangabali"],
  33: ["Pabna Sadar", "Ishwardi", "Bhangura", "Chatmohar", "Faridpur", "Sujanagar", "Bera", "Atgharia", "Santhia"],
  34: ["Pirojpur Sadar", "Nazirpur", "Nesarabad", "Kawkhali", "Bhandaria", "Mathbaria", "Indurkani"],
  35: ["Faridpur Sadar", "Alfadanga", "Boalmari", "Sadorpur", "Nagarkanda", "Bhanga", "Charbhadrasan", "Madhukhali", "Saltha"],
  36: ["Feni Sadar", "Chhagalnaiya", "Parshuram", "Fulgazi", "Daganbhuiyan", "Sonagazi"],
  37: ["Bogra Sadar", "Shajahanpur", "Sherpur", "Dhunat", "Nandigram", "Kahalu", "Adamdighi", "Dupchanchia", "Shibganj", "Sonatala", "Gabtoli", "Sariakandi"],
  38: ["Barguna Sadar", "Amtali", "Patharghata", "Bamna", "Betagi", "Taltali"],
  39: ["Barishal Sadar", "Bakerganj", "Babuganj", "Wazirpur", "Banaripara", "Gournadi", "Agailjhara", "Muladi", "Mehendiganj", "Hizla"],
  40: ["Bagerhat Sadar", "Fakirhat", "Mollahat", "Chitalmari", "Kachua", "Rampal", "Mongla", "Sarankhola", "Morrelganj"],
  
  41: ["Bandarban Sadar", "Ruma", "Thanchi", "Rowangchhari", "Lama", "Alikadam", "Naikhongchhari"],
  42: ["Brahmanbaria Sadar", "Kasba", "Nasirnagar", "Sarail", "Ashuganj", "Akhaura", "Nabinnagar", "Bancharampur", "Bijoynagar"],
  43: ["Bhola Sadar", "Borhanuddin", "Char Fasson", "Lalmohan", "Tazumuddin", "Daulatkhan", "Manpura"],
  44: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
  45: ["Madaripur Sadar", "Shibchar", "Kalkini", "Rajoir", "Dasar"],
  46: ["Manikganj Sadar", "Singair", "Ghior", "Saturia", "Harirampur", "Shibalaya", "Daulatpur"],
  47: ["Munshiganj Sadar", "Sreenagar", "Sirajdikhan", "Louhajang", "Tongibari", "Gajaria"],
  48: ["Meherpur Sadar", "Gangni", "Mujibnagar"],
  49: ["Moulvibazar Sadar", "Sreemangal", "Rajnagar", "Kulaura", "Barlekha", "Kamalganj", "Juri"],
  50: ["Mymensingh Sadar", "Muktagachha", "Fulbaria", "Trishal", "Bhaluka", "Gafargaon", "Ishwarganj", "Nandail", "Gauripur", "Phulpur", "Dhobaura", "Haluaghat", "Tarakanda"],
  
  51: ["Jashore Sadar", "Jhikargachha", "Sharsha", "Chougachha", "Keshabpur", "Manirampur", "Abhaynagar", "Bagherpara"],
  52: ["Rangpur Sadar", "Mithapukur", "Pirganj", "Pirgachha", "Kaunia", "Gangachhara", "Badarganj", "Tapadhan"],
  53: ["Rangamati Sadar", "Kaptai", "Kawkhali", "Baghaichhari", "Langadu", "Naniarchar", "Rajasthali", "Jurachhari", "Barkal", "Bilaichhari"],
  54: ["Rajbari Sadar", "Goalanda", "Pangsha", "Baliakandi", "Kalukhali"],
  55: ["Rajshahi Sadar", "Paba", "Tanore", "Godagari", "Mohanpur", "Bagmara", "Durgapur", "Puthia", "Charghat", "Bagha"],
  56: ["Lakshmipur Sadar", "Raipur", "Ramganj", "Ramgati", "Kamalnagar"],
  57: ["Lalmonirhat Sadar", "Kaliganj", "Hatibandha", "Patgram", "Aditmari"],
  58: ["Shariatpur Sadar", "Damudya", "Naria", "Zajira", "Bhederganj", "Gosairhat"],
  59: ["Sherpur Sadar", "Nalitabari", "Jhenaigati", "Nakla", "Sreebardi"],
  60: ["Satkhira Sadar", "Kalaroa", "Tala", "Ashashuni", "Shyamnagar", "Kaliganj", "Debhata"],
  61: ["Sirajganj Sadar", "Belkuchi", "Chauhali", "Kamarkhanda", "Kazipur", "Rayganj", "Shahzadpur", "Tarash", "Ullapara"],
  62: ["Sylhet Sadar", "Beanibazar", "Golapganj", "Fenchuganj", "Balaganj", "Biswanath", "Companiganj", "Gauripur", "Jaintiapur", "Kanaighat", "Zakiganj", "South Surma", "Osmaninagar"],
  63: ["Sunamganj Sadar", "Chhatak", "Jagannathpur", "Derai", "Shalla", "Dharampasha", "Tahirpur", "Bishwamavpur", "Dowarabazar", "Jamalganj", "Madhyanagar"],
  64: ["Habiganj Sadar", "Nabiganj", "Bahubal", "Azmiriganj", "Baniachachong", "Lakhai", "Chunarughat", "Madhabpur", "Shayestaganj"]
};