export const districts = [

    { "id": 21, "name": "ঢাকা", "en_name": "Dhaka" },
    { "id": 11, "name": "চট্টগ্রাম", "en_name": "Chattogram" },
    { "id": 1, "name": "কক্সবাজার", "en_name": "Cox's Bazar" },
    { "id": 2, "name": "কিশোরগঞ্জ", "en_name": "Kishoreganj" },
    { "id": 3, "name": "কুমিল্লা", "en_name": "Cumilla" },
    { "id": 4, "name": "কুষ্টিয়া", "en_name": "Kushtia" },
    { "id": 5, "name": "কুড়িগ্রাম", "en_name": "Kurigram" },
    { "id": 6, "name": "খাগড়াছড়ি", "en_name": "Khagrachhari" },
    { "id": 7, "name": "খুলনা", "en_name": "Khulna" },
    { "id": 8, "name": "গাইবান্ধা", "en_name": "Gaibandha" },
    { "id": 9, "name": "গাজীপুর", "en_name": "Gazipur" },
    { "id": 10, "name": "গোপালগঞ্জ", "en_name": "Gopalganj" },
    { "id": 12, "name": "চাঁদপুর", "en_name": "Chandpur" },
    { "id": 13, "name": "চাঁপাইনবাবগঞ্জ", "en_name": "Chapainawabganj" },
    { "id": 14, "name": "চুয়াডাঙ্গা", "en_name": "Chuadanga" },
    { "id": 15, "name": "জামালপুর", "en_name": "Jamalpur" },
    { "id": 16, "name": "জয়পুরহাট", "en_name": "Joypurhat" },
    { "id": 17, "name": "ঝালকাঠি", "en_name": "Jhalokati" },
    { "id": 18, "name": "ঝিনাইদহ", "en_name": "Jhenaidah" },
    { "id": 19, "name": "টাঙ্গাইল", "en_name": "Tangail" },
    { "id": 20, "name": "ঠাকুরগাঁও", "en_name": "Thakurgaon" },
    { "id": 22, "name": "দিনাজপুর", "en_name": "Dinajpur" },
    { "id": 23, "name": "নওগাঁ", "en_name": "Naogaon" },
    { "id": 24, "name": "নরসিংদী", "en_name": "Narsingdi" },
    { "id": 25, "name": "নাটোর", "en_name": "Natore" },
    { "id": 26, "name": "নারায়ণগঞ্জ", "en_name": "Narayanganj" },
    { "id": 27, "name": "নীলফামারী", "en_name": "Nilphamari" },
    { "id": 28, "name": "নেত্রকোনা", "en_name": "Netrokona" },
    { "id": 29, "name": "নোয়াখালী", "en_name": "Noakhali" },
    { "id": 30, "name": "নড়াইল", "en_name": "Narail" },
    { "id": 31, "name": "পঞ্চগড়", "en_name": "Panchagarh" },
    { "id": 32, "name": "পটুয়াখালী", "en_name": "Patuakhali" },
    { "id": 33, "name": "পাবনা", "en_name": "Pabna" },
    { "id": 34, "name": "পিরোজপুর", "en_name": "Pirojpur" },
    { "id": 35, "name": "ফরিদপুর", "en_name": "Faridpur" },
    { "id": 36, "name": "ফেনী", "en_name": "Feni" },
    { "id": 37, "name": "বগুড়া", "en_name": "Bogra" },
    { "id": 38, "name": "বরগুনা", "en_name": "Barguna" },
    { "id": 39, "name": "বরিশাল", "en_name": "Barishal" },
    { "id": 40, "name": "বাগেরহাট", "en_name": "Bagerhat" },
    { "id": 41, "name": "বান্দরবান", "en_name": "Bandarban" },
    { "id": 42, "name": "ব্রাহ্মণবাড়িয়া", "en_name": "Brahmanbaria" },
    { "id": 43, "name": "ভোলা", "en_name": "Bhola" },
    { "id": 44, "name": "মাগুরা", "en_name": "Magura" },
    { "id": 45, "name": "মাদারীপুর", "en_name": "Madaripur" },
    { "id": 46, "name": "মানিকগঞ্জ", "en_name": "Manikganj" },
    { "id": 47, "name": "মুন্সিগঞ্জ", "en_name": "Munshiganj" },
    { "id": 48, "name": "মেহেরপুর", "en_name": "Meherpur" },
    { "id": 49, "name": "মৌলভীবাজার", "en_name": "Moulvibazar" },
    { "id": 50, "name": "ময়মনসিংহ", "en_name": "Mymensingh" },
    { "id": 51, "name": "যশোর", "en_name": "Jashore" },
    { "id": 52, "name": "রংপুর", "en_name": "Rangpur" },
    { "id": 53, "name": "রাঙামাটি", "en_name": "Rangamati" },
    { "id": 54, "name": "রাজবাড়ী", "en_name": "Rajbari" },
    { "id": 55, "name": "রাজশাহী", "en_name": "Rajshahi" },
    { "id": 56, "name": "লক্ষ্মীপুর", "en_name": "Lakshmipur" },
    { "id": 57, "name": "লালমনিরহাট", "en_name": "Lalmonirhat" },
    { "id": 58, "name": "শরীয়তপুর", "en_name": "Shariatpur" },
    { "id": 59, "name": "শেরপুর", "en_name": "Sherpur" },
    { "id": 60, "name": "সাতক্ষীরা", "en_name": "Satkhira" },
    { "id": 61, "name": "সিরাজগঞ্জ", "en_name": "Sirajganj" },
    { "id": 62, "name": "সিলেট", "en_name": "Sylhet" },
    { "id": 63, "name": "সুনামগঞ্জ", "en_name": "Sunamganj" },
    { "id": 64, "name": "হবিগঞ্জ", "en_name": "Habiganj" }
  ]
  

  export const upazilas: { [key: number]: string[] } = {
    1: ["কক্সবাজার সদর", "উখিয়া", "টেকনাফ", "রামু", "চকরিয়া", "মহেশখালী", "পেকুয়া", "কুতুবদিয়া", "ঈদগাঁও"],
    2: ["কিশোরগঞ্জ সদর", "করিমগঞ্জ", "তাড়াইল", "হোসেনপুর", "কটিয়াদী", "কুলিয়ারচর", "ভৈরব", "নিকলী", "বাজিতপুর", "ইটনা", "মিঠামইন", "অষ্টগ্রাম", "পাকুন্দিয়া"],
    3: ["কুমিল্লা সদর", "লাকসাম", "দেবিদ্বার", "মুরাদনগর", "দাউদকান্দি", "চৌদ্দগ্রাম", "বরুড়া", "বুড়িচং", "ব্রাহ্মণপাড়া", "চাঁন্দিনা", "হোমনা", "লাঙ্গলকোট", "মেঘনা", "মনোহরগঞ্জ", "তিতাস", "সদর দক্ষিণ"],
    4: ["কুষ্টিয়া সদর", "কুমারখালী", "খোকসা", "মিরপুর", "দৌলতপুর", "ভেড়ামারা"],
    5: ["কুড়িগ্রাম সদর", "উলিপুর", "চিলমারী", "রুমারী", "চর রাজিবপুর", "নাগেশ্বরী", "ভুরুঙ্গামারী", "রাজারহাট", " কুড়িগ্রাম ফুলবাড়ী"],
    6: ["খাগড়াছড়ি সদর", "দিঘীনালা", "পানছড়ি", "মাটিরাঙ্গা", "মহালছড়ি", "মানিকছড়ি", "রামগড়", "লক্ষ্মীছড়ি", "গুইমারা"],
    7: ["খুলনা সদর", "কয়রা", "ডুমুরিয়া", "তেরখাদা", "দাকোপ", "দিঘলিয়া", "পাইকগাছা", "ফুলতলা", "বটিয়াঘাটা", "রূপসা"],
    8: ["গাইবান্ধা সদর", "সাদুল্লাপুর", "পলাশবাড়ী", "সুন্দরগঞ্জ", "সাঘাটা", "গোবিন্দগঞ্জ", "ফুলছড়ি"],
    9: ["গাজীপুর সদর", "কালিয়াকৈর", "কালীগঞ্জ", "কপাসিয়া", "শ্রীপুর"],
    10: ["গোপালগঞ্জ সদর", "কোটালীপাড়া", "টুঙ্গিপাড়া", "কাশিয়ানী", "مুকসুদপুর"],
    11: ["চট্টগ্রাম সিটি (Chittagong City)", "আনোয়ারা উপজেলা সদর (Anwara Upazila sadar)", "বাঁশখালী উপজেলা সদর (Banshkhali Upazila sadar)", "বোয়ালখালী উপজেলা সদর (Boalkhali Upazila Sadar)", "চন্দনাইশ উপজেলা সদর (Chandanaish Upazila Sadar)", "ফটিকছড়ি উপজেলা সদর (Fatikchhari Upazila Sadar)", "হাটহাজারী উপজেলা সদর (Hathazari Upazila Sadar)", "লোহাগাড়া উপজেলা সদর (Lohagara Upazila Sadar CTG)", "মীরসরাই (Mirsharai)", "পটিয়া উপজেলা সদর (Patiya Upazila Sadar)", 
  "রাঙ্গুনিয়া উপজেলা সদর (Rangunia Upazila Sadar)", "রাউজান উপজেলা সদর (Raozan Upazila Sadar)", "সাতকানিয়া উপজেলা সদর (Satkania Upazila Sadar)", "সীতাকুণ্ড (Sitakund)", "কর্নেল হাট (Cornel Hat Chittagong)", "পতেঙ্গা চট্টগ্রাম (Potenga chittagong)", "চট্টগ্রাম প্রকৌশল ও প্রযুক্তি বিশ্ববিদ্যালয় (CUET)", "অক্সিজেন মোড় (Oxyzen Mor)", "হালিশহর (Halishohor)", "এ কে খান (AK Khan)", 
  "পাহাড়তলী (Pahartoli)", "আকবর শাহ (Akbor Shah)", "চট্টগ্রাম ইপিজেড (Chittagong EPZ)", "আগ্রাবাদ (Agrabad)", "চট্টগ্রাম নিউ মার্কেট (Chittagong New market)", "আন্দরকিল্লা (Andarkilla)", "চকবাজার (Chowkbazar)", "সদরঘাট (Sadarghat)", "জিইসি মোড় (GEC Mor)", "খুলশী (Khulshi)", 
  "২ নম্বর গেট (2 no gate)", "পাঁচলাইশ (Panchlaish)", "বায়েজিদ বোস্তামী (Bayzid Bostami)", "নয়াবাজার (Noyabazar)", "কদমতলী (Kodomtoli)", "দেওয়ানহাট (Dewanhat)", "সাগরিকা (Sagorika)", "অলঙ্কার (Alonkar)", "ফয়েজ লেক (Foy's Lake)", "মুরাদপুর (Muradpur)", 
  "আতুরের ডিপো (Aturar Depot)", "বাকলিয়া (Bakoliya)", "মির্জারপুল (Mirjarpol)", "বহদ্দারহাট (Boddarhat)", "মাদারবাড়ী (Madarbari)", "শেখ মুজিব রোড (SK Mujib Road)", "চৌমুহনী (Chowmohoni)", "ডবলমুরিং (Double Mooring)", "আছাদগঞ্জ (Asadganj)", "খাতুনগঞ্জ (Khatunganj)", 
  "হাটহাজারী (Hathazari)", "চান্দগাঁও (Chandgaon)", "কোতোয়ালী (Kotwali)", "রাউজান (Raozan)", "সাতকানিয়া (Satkania)", "আনোয়ারা (Anowara)", "বাঁশখালী (Banshkhali)", "কর্ণফুলী (Karnaphuli)", "বোয়ালখালী (Boalkhali)", "চন্দনাইশ (Chandanaish)", 
  "পটিয়া (Patiya)", "চট্টগ্রাম বন্দর (Chittagong Port)", "ডবলমুরিং (Double Mooring)", "পতেঙ্গা (Patenga)", "বায়েজিদ বোস্তামী (Bayejid Bostami)", "বাকলিয়া (Bakalia)", "ভুজপুর (Bhujpur)", "চৌধুরী হাট (Chowdhury Hat)", "রাঙ্গুনিয়া (Rangunia)", "সীতাকুণ্ড (Sitakunda)", 
  "ফটিকছড়ি (Fatikchhari)", "মীরসরাই (Mirsharai)", "সন্দ্বীপ (Sandwip)", "লালখান বাজার (Lalkhan Bazar)", "গরীবুল্লাহ শাহ মাজার (Garibullah Shah Mazar)", "দামপাড়া (Dampara)", "জনতা কলোনি (Jonota Colony)", "মনসুরাবাদ (Monsurabad)", "ঝাউতলা (Jhautola)", "নাসিরাবাদ (Nasirabad)", 
  "সুগন্ধা আবাসিক এলাকা (Shugandha Residential)", "ষোলশহর (Sholoshahor)", "রোজ ভ্যালি আবাসিক এলাকা (Rose Vally R/A)", "অক্সিজেন (Oxygen)", "চট্টগ্রাম সেনানিবাস (CTG Cantonment)", "মেহেদীবাগ (Mehedibag)", "কাজীর দেউড়ী (Kajir Dewri)", "জামালখান (Jamalkhan)", "ইপিজেড (EPZ)", "ফিরিঙ্গী বাজার (Firingi Bazar)", 
  "পাথরঘাটা (Pathar Ghata)", "পারৈকোড়া (Paroikora)", "পারৈকোড়া (Paroikora)", "আল-আমিন বারীয়া মাদ্রাসা (Al- Amin Baria Madra)", "গাছবাড়িয়া (Gachbaria)", "পূর্ব জোয়ারা (East Joara)", "বারমা (Barma)", "দোহাজারী (Dohazari)", "রামগড় হেড অফিস (Ramghar Head Office)", "হারুয়ালছড়ি (Harualchhari)", 
  "নাজিরহাট (Najirhat)", "জারাছড়ি (Jarachhari)", "কালীপুর (Kalipur)", "কালীপুর (Kalipur)", "গোরাকঘাট (Gorakghat)", "লংগদু (Longachh)", "মারিশ্যা (Marishya)", "বরকল (Barakal)", "পদুয়া (Padua)", "নিউজিল্যান্ড/আনন্দবাজার (Anandabazar)", 
  "জগন্নাথ হাট (jagannath Hat)", "বি.আই.টি পোস্ট অফিস (B.I.T Post Office)", "ফতেপুর (Fatepur)", "বীনাজুরী (Beenajuri)", "গহিরা (Gahira)", "কুণ্ডেশ্বরী (Kundeshwari)", "مহামুনি (Mohamuni)", "দেওয়ানপুর (Dewanpur)", "রামপুরা (Rampura)", "চট্টগ্রাম পলিটেকনিক ইনস্টিটিউট (Chitt. Politechnic In)", 
  "মধ্য পতেঙ্গা (Middle Patenga)", "জলদিয়া মেরিন একাডেমি (Jaldia Merine Accade)", "উত্তর কাট্টলী (North Katuli)", "চট্টগ্রাম সেলার্স কলোনি (Chitt. Sailers Colon)", "চট্টগ্রাম বিমানবন্দর (Chittagong Airport)", "উত্তর হালিশহর (North Halishahar)", "চট্টগ্রাম বিমানবন্দর (Chittagong Airport)", "উত্তর হালিশহর (North Halishahar)", "খান বাহাদুর (Khan Bahadur)", "गुनागडी (Gunagari)", 
  "জলদিয়া মেরিন একাডেমি (Jaldia Merine Accade)", "বাণীগ্রাম (Banigram)", "ইউনুস নগর (Yunus Nagar)", "ফতেয়াবাদ (Fatahabad)", "গড়দুয়ারা (Gorduara)", "কাটিরহাট (Katirhat)", "মাদ্রাসা (Madrasa)", "নূরালীবাড়ী (Nuralibari)", "রাজস্থলী (Rajsthali)", "কানুনগোপাড়া (Kanungopara)", 
  "সারোয়াতলী (Saroatoli)", "ইকবাল পার্ক (Iqbal Park)", "বাইতুল ইজ্জত (Baitul Ijjat)", "বেতবুনিয়া (Betbunia)", "কালামপাতি (Kalampati)", "নানিয়ারচর (Nanichhar)", "ওয়ার্ড নম্বর-১৫ (Ward No-15)", "ওয়ার্ড নম্বর-১৬ অংশ (Ward No-16 Part)", "ওয়ার্ড নম্বর-২০ (Ward No-20)", "ওয়ার্ড নম্বর-২১ (Ward No-21)", 
  "ওয়ার্ড নম্বর-২২ (Ward No-22)", "ওয়ার্ড নম্বর-৩১ (Ward No-31)", "ওয়ার্ড নম্বর-৩২ (Ward No-32)", "ওয়ার্ড নম্বর-৩৩ (Ward No-33)", "ওয়ার্ড নম্বর-৩৪ (Ward No-34)", "ওয়ার্ড নম্বর-৩৫ অংশ (Ward No-35 Part)", "ওয়ার্ড নম্বর-১৭ (Ward No-17)", "ওয়ার্ড নম্বর-১৮ (Ward No-18)", "ওয়ার্ড নম্বর-১৯ (Ward No-19)", "ওয়ার্ড নম্বর-৩৫ অংশ (Ward No-35 Part)", 
  "ওয়ার্ড নম্বর-০৪ (Ward No-04)", "ওয়ার্ড নম্বর-০৫ (Ward No-05)", "ওয়ার্ড নম্বর-০৬ (Ward No-06)", "ওয়ার্ড নম্বর-৩৭ (Ward No-37)", "ওয়ার্ড নম্বর-৩৮ (Ward No-38)", "ওয়ার্ড নম্বর-৩৯ (Ward No-39)", "ওয়ার্ড নম্বর-২৩ (Ward No-23)", "ওয়ার্ড নম্বর-২৪ অংশ (Ward No-24 Part)", "ওয়ার্ড নম্বর-২৭ (Ward No-27)", "ওয়ার্ড নম্বর-২৭ (Ward No-27)", 
  "ওয়ার্ড নম্বর-২৮ (Ward No-28)", "ওয়ার্ড নম্বর-২৯ (Ward No-29)", "ওয়ার্ড নম্বর-৩০ (Ward No-30)", "ওয়ার্ড নম্বর-৩৬ (Ward No-36)", "ওয়ার্ড নম্বর-২৪ অংশ (Ward No-24Part)", "ওয়ার্ড নম্বর-১১ অংশ (Ward No-11 Part)", "ওয়ার্ড নম্বর-২৫ (Ward No-25)", "ওয়ার্ড নম্বর-২৬ (Ward No-26)", "ওয়ার্ড নম্বর-০৮ অংশ (Ward No-08Part)", "ওয়ার্ড নম্বর-০৯ (Ward No-09)", 
  "ওয়ার্ড নম্বর-১৩ (Ward No-13)", "ওয়ার্ড নম্বর-১৪ (Ward No-14)", "ওয়ার্ড নম্বর-১০ (Ward No-10)", "ওয়ার্ড নম্বর-১২ (Ward No-12)", "ওয়ার্ড নম্বর-০৮ অংশ (Ward No-08Part)", "ওয়ার্ড নম্বর-০৭ (Ward No-07)", "ওয়ার্ড নম্বর-১৬ অংশ (Ward No-16 Part)", "হালিশহর (Halishohor)", "ইপিজেড (EPZ)", "হালিশহর (Halishohor)", 
  "ইপিজেড (EPZ)", "ওয়াজেদিয়া (Wajediya)", "বালুচরা (baluchora)", "রাণীরহাট (ranirhat)"],
    12: ["চাঁদপুর সদর", "হাজীগঞ্জ", "কচুয়া", "ফরিদগঞ্জ", "মতলব উত্তর", "মতলব দক্ষিণ", "হাইমচর", "শাহরাস্তি"],
    13: ["চাঁপাইনবাবগঞ্জ সদর", "শিবগঞ্জ", "গোমস্তাপুর", "নাচোল", "ভোলাহাট"],
    14: ["চুয়াডাঙ্গা সদর", "আলমডাঙ্গা", "দামুড়হুদা", "জীবননগর"],
    15: ["জামালপুর সদর", "মেলান্দহ", "ইসলামপুর", "দেওয়ানগঞ্জ", "সরিষাবাড়ী", "মাদারগঞ্জ", "বকশীগঞ্জ"],
    16: ["জয়পুরহাট সদর", "পাঁচবিবি", "আক্কেলপুর", "কালাই", "ক্ষেতলাল"],
    17: ["ঝালকাঠি সদর", "নলছিটি", "রাজাপুর", "কাঠালিয়া"],
    18: ["ঝিনাইদহ সদর", "শৈলকুপা", "হরিণাকুণ্ডু", "কালীগঞ্জ", "কোটচাঁদপুর", "মহেশপুর"],
    19: ["টাঙ্গাইল সদর", "কালিহাতী", "ঘাটাইল", "বাসাইল", "গোপালপুর", "মির্জাপুর", "নাগরপুর", "مধুপুর", "সখিপুর", "দেলদুয়ার", "ধনবাড়ী", "ভূঞাপুর"],
    20: ["ঠাকুরগাঁও সদর", "পীরগঞ্জ", "বালীয়াডাঙ্গী", "রাণীশংকৈল", "হরিপুর"],
    
    21: ["সাভার (Savar)", "আশুলিয়া (Ashulia)", "হেমায়েতপুর (Hemayetpur)", "নবীনগর (Nabinagar)", "ধামরাই (Dhamrai)", "কেরানীগঞ্জ (Keraniganj)", "জিঞ্জিরা (Zinzira)", "নবাবগঞ্জ (Nawabganj)", "দোহার (Dohar)", "আমীনবাজার (Amin Bazar)",
  "মিরপুর ১ (Mirpur 1)", "মিরপুর ২ (Mirpur 2)", "মিরপুর ১০ (Mirpur 10)", "মিরপুর ১১ (Mirpur 11)", "মিরপুর ১২ (Mirpur 12)", "মিরপুর ১৩ (Mirpur 13)", "মিরপুর ১৪ (Mirpur 14)", "মিরপুর ডিওএইচএস (Mirpur DOHS)", "মিরপুর ৬০ ফিট (Mirpur 60 Feet)", "শেওড়াপাড়া (Shewrapara)",
  "কাজীপাড়া (Kazipara)", "পল্লবী (Pallabi)", "রূপনগর (Rupnagar)", "শাহ আলী (Shah Ali)", "কাফরুল (Kafrul)", "আগারগাঁও (Agargaon)", "তালতলা (Taltola)", "কল্যাণপুর (Kallayanpur)", "দারুস সালাম (Darus Salam)", "গাবতলী (Gabtoli)",
  "উত্তরা সেক্টর ১-১০ (Uttara Sector 1-10)", "উত্তরা সেক্টর ১১-১৮ (Uttara Sector 11-18)", "আব্দুল্লাহপুর (Abdullahpur)", "উত্তরাখান (Uttar Khan)", "দক্ষিণখান (Dakkhin Khan)", "বিমানবন্দর এলাকা (Airport Area)", "আশকোনা (Ashkona)", "খিলক্ষেত (Khilket)", "নিকুঞ্জ (Nikunjo)", "কুড়িল (Kuril)",
  "বসুন্ধরা আবাসিক এলাকা (Bashundhara RA)", "বারিধারা আবাসিক এলাকা (Baridhara RA)", "বারিধারা ডিওএইচএস (Baridhara DOHS)", "নদ্দা (Norda)", "ভাটারা (Vatara)", "বাড্ডা (Badda)", "মেরুল বাড্ডা (Merul Badda)", "শাহজাদপুর (Shahjadpur)", "সাতারকুল (Satarkul)", "পূর্বাচল ৩০০ ফিট (Purbachal 300 Feet)",
  "গুলশান ১  (Gulshan 1)", "গুলশান ২ (Gulshan 2)", "বনানী (Banani)", "বনানী ডিওএইচএস (Banani DOHS)", "মহাখালী (Mohakhali)", "মহাখালী ডিওএইচএস (Mohakhali DOHS)", "নিকেতন (Niketon)", "তেজগাঁও (Tejgaon)", "তেজগাঁও শিল্প এলাকা (Tejgaon Industrial Area)", "কারওয়ান বাজার (Kawran Bazar)",
  "ফার্মগেট (Farmgate)", "পান্থপথ (Panthapath)", "গ্রিন রোড (Green Road)", "হাতিরপুল (Hatirpool)", "ধানমন্ডি (Dhanmondi)", "সোবহানবাগ (Sobhanbag)", "কলাবাগান (Kalabagan)", "কাঠালবাগান (Kathalbagan)", "সায়েন্স ল্যাব (Science Lab)", "এলিফ্যান্ট রোড (Elephant Road)",
  "মোহাম্মদপুর (Mohammadpur)", "আদাবর (Adabor)", "শেখেরটেক (Shekertek)", "শিয়া মসজিদ (Shia Masjid)", "বছিলা(Bosila)", "ঢাকা উদ্যান (Dhaka Uddan)", "লালমাটিয়া (Lalmatia)", "রায়েরবাজার (Rayerbazar)", "জিগাতলা (Zigatola)", "হাজারীবাগ (Hazaribagh)",
  "লালবাগ (Lalbagh)", "চকবাজার (Chawkbazar)", "কোতোয়ালী (Kotwali)", "বাবু বাজার (Babu Bazar)", "নবাবপুর (Nawabpur)", "সদরঘাট (Sodorghat)", "সূত্রাপুর (Sutrapur)", "গেন্ডারিয়া (Gendaria)", "ওয়ারী (Wari)", "টিকাটুলী (Tikatuli)",
  "যাত্রাবাড়ী (Jatrabari)", "শনির আখড়া (Shonir Akhra)", "রায়েরবাগ (Rayerbagh)", "মাতুয়াইল (Matuail)", "দনিয়া (Donia)", "ডেমরা (Demra)", "শ্যামপুর (Shyampur)", "কামরাঙ্গীরচর (Kamrangirchor)", "পোস্তগোলা (Postogola)", "জুড়াইন (Jurain)",
  "সবুজবাগ (Sabujbagh)", "বাসাবো (Bashabo)", "খিলগাঁও (Khilgaon)", "গোড়ান (Goran)", "রামপুরা (Rampura)", "বনশ্রী (Banasree)", "আফতাবনগর (Aftabnagar)", "মালিবাগ (Malibagh)", "মৌচাক (Mouchak)", "মগবাজার (Moghbazar)",
  "সিদ্ধেশ্বরী (Siddheswari)", "বেইলি রোড (Bailey Road)", "শান্তিনগর (Shantinagar)", "কাকরাইল (Kakrail)", "পল্টন (Paltan)", "মতিঝিল (Motijheel)", "দিলকুশা (Dilkusha)", "কমলাপুর (Komlapur)", "শাহজাহানপুর (Shahjahanpur)", "মুগদা (Mugda)",
  "সায়দাবাদ (Sayedabad)", "রমনা (Romna)", "শাহবাগ (Shahbagh)", "ঢাকা বিশ্ববিদ্যালয় এলাকা (Dhaka University Area)", "নিউমার্কেট (New Market)", "আজিমপুর (Azimpur)", "নীলক্ষেত (Nilkhet)", "বক্সিবাজার (Bakshibazar)", "সেগুনবাগিচা (Segunbagicha)", "ঢাকা সেনানিবাস (Dhaka Cantonment)"],

    22: ["দিনাজপুর সদর", "বিরামপুর", "নবাবগঞ্জ", "বীরগঞ্জ", "বোচাগঞ্জ","চিরিরবন্দর", "ফুলবাড়ী", "কাহারোল", "খানসামা", "পার্বতীপুর", "হাকিমপুর", "ঘোড়াঘাট"],
    23: ["নওগাঁ সদর", "পত্নীতলা", "ধামইরহাট", "মহাদেবপুর", "পোরশা", "সাপাহার", "বদলগাছী", "আত্রাই", "রানীনগর", "নিয়ামতপুর", "মান্দা"],
    24: ["নরসিংদী সদর", "পলাশ", "শিবপুর", "মনোহরদী", "বেলাবো", "রায়পুরা"],
    25: ["নাটোর সদর", "বাগাতিপাড়া", "বড়াইগ্রাম", "গুরুদাসপুর", "লালপুর", "সিংড়া", "নলডাঙ্গা"],
    26: ["নারায়ণগঞ্জ সদর", "বন্দর", "আড়াইহাজার", "রূপগঞ্জ", "সোনারগাঁও"],
    27: ["নীলফামারী সদর", "সৈয়দপুর", "জলঢাকা", "কিশোরগঞ্জ", "ডোমার", "ডিমলা"],
    28: ["নেত্রকোনা সদর", "বারহাট্টা", "কলমাকান্দা", "দুর্গাপুর", "কেন্দুয়া", "মদন", "মোহনগঞ্জ", "পূর্বধলা", "খালিয়াজুরী", "আটপাড়া"],
    29: ["নোয়াখালী সদর", "কোম্পানীগঞ্জ", "বেগমগঞ্জ", "চাটখিল", "সেনবাগ", "হাতিয়া", "সুবর্ণচর", "সোনাইমুড়ী", "কবিরহাট"],
    30: ["নড়াইল সদর", "লোহাগড়া", "কালিয়া"],

    31: ["পঞ্চগড় সদর", "তেঁতুলিয়া", "বোদা", "দেবীগঞ্জ", "আটোয়ারী"],
    32: ["পটুয়াখালী সদর", "বাউফল", "গলাচিপা", "দশমিনা", "মির্জাগঞ্জ", "কলাপাড়া", "দুমকি", "রাঙ্গাবালী"],
    33: ["পাবনা সদর", "ঈশ্বরদী", "ভাঙ্গুড়া", "চাটমোহর", "ফরিদপুর", "সুজানগর", "বেড়া", "আটঘরিয়া", "সাথিয়া"],
    34: ["পিরোজপুর সদর", "নাজিরপুর", "নেছারাবাদ", "কাওখালী", "ভাণ্ডারিয়া", "মঠবাড়িয়া", "ইন্দুরকানী"],
    35: ["ফরিদপুর সদর", "আলফাডাঙ্গা", "বোয়ালমারী", "সদরপুর", "নগরকান্দা", "ভাঙ্গা", "চরভদ্রাসন", "মধুখালী", "সালথা"],
    36: ["ফেনী সদর", "ছাগলনাইয়া", "পরশুরাম", "ফুলগাজী", "দাগনভূঁইয়া", "সোনাগাজী"],
    37: ["বগুড়া সদর", "শাজাহানপুর", "শেরপুর", "ধুনট", "নন্দীগ্রাম", "কাহালু", "আদমদিঘী", "দুপচাঁচিয়া", "শিবগঞ্জ", "সোনাতলা", "গাবতলী", "সারিয়াকান্দি"],
    38: ["বরগুনা সদর", "আমতলী", "পাথরঘাটা", "বামনা", "বেতাগী", "তালতলী"],
    39: ["বরিশাল সদর", "বাকেরগঞ্জ", "বাবুগঞ্জ", "উজিরপুর", "বানারীপাড়া", "গৌরনদী", "আগৈলঝারা", "মুলাদী", "হিজলা", "মেহেন্দিগঞ্জ"],
    40: ["বাগেরহাট সদর", "ফকিরহাট", "মোল্লাহাট", "চিতলমারী", "কচুয়া", "রামপাল", "মোংলা", "শরণখোলা", "মোড়েলগঞ্জ"],
    
    41: ["বান্দরবান সদর", "রুমা", "থানচি", "রোয়াংছড়ি", "লামা", "আলীকদম", "নাইক্ষ্যংছড়ি"],
    42: ["ব্রাহ্মণবাড়িয়া সদর", "কসবা", "নাসিরনগর", "সরাইল", "আশুগঞ্জ", "আখাউড়া", "নবীনগর", "বাঞ্ছারামপুর", "বিজয়নগর"],
    43: ["ভোলা সদর", "বোরহানউদ্দিন", "চরফ্যাশন", "লালমোহন", "তজুমদ্দিন", "দৌলতখান", "মনপুরা"],
    44: ["মাগুরা সদর", "মহম্মদপুর", "শালিখা", "শ্রীপুর"],
    45: ["মাদারীপুর সদর", "শিবচর", "কালকিনি", "রাজৈর", "ডাসার"],
    46: ["মানিকগঞ্জ সদর", "সিংগাইর", "ঘিওর", "সাটুরিয়া", "হরিরামপুর", "শিবালয়", "দৌলতপুর"],
    47: ["মুন্সিগঞ্জ সদর", "শ্রীনগর", "সিরাজদিখান", "লৌহজং", "টংগিবাড়ী", "গজারিয়া"],
    48: ["মেহেরপুর সদর", "গাংনী", "মুজিবনগর"],
    49: ["মৌলভীবাজার সদর", "শ্রীমঙ্গল", "রাজনগর", "কুলাউড়া", "বড়লেখা", "কমলগঞ্জ", "জুড়ী"],
    50: ["ময়মনসিংহ সদর", "মুক্তাগাছা", "ফুলবাড়ীয়া", "ত্রিশাল", "ভালুকা", "গফরগাঁও", "ঈশ্বরগঞ্জ", "নান্দাইল", "গৌরীপুর", "ফুলপুর", "ধোবাউড়া", "হালুয়াঘাট", "তারাকান্দা"],
    
    51: ["যশোর সদর", "ঝিকরগাছা", "শার্শা", "চৌগাছা", "কেশবপুর", "মণিরামপুর", "অভয়নগর", "বাঘেরপাড়া"],
    52: ["রংপুর সদর", "মিঠাপুকুর", "পীরগঞ্জ", "পীরগাছা", "কাউনিয়া", "গঙ্গাচড়া", "বদরগঞ্জ", "তপাধন"],
    53: ["রাঙামাটি সদর", "কাপ্তাই", "কাউখালী", "বাঘাইছড়ি", "লংগদু", "নানিয়ারচর", "রাজস্থলী", "জুরাছড়ি", "বরকল", "বিলাইছড়ি"],
    54: ["রাজবাড়ী সদর", "গোয়ালন্দ", "পাংশা", "বালিয়াকান্দি", "কালুখালী"],
    55: ["রাজশাহী সদর", "পবা", "তানোর", "গোদাগাড়ী", "মোহনপুর", "বাগমারা", "দুর্গাপুর", "পুঠিয়া", "চারঘাট", "বাঘা"],
    56: ["লক্ষ্মীপুর সদর", "রায়পুর", "রামগঞ্জ", "রামগতি", "কমলনগর"],
    57: ["লালমনিরহাট সদর", "কালীগঞ্জ", "হাতীবান্ধা", "পাটগ্রাম", "আদিতমারী"],
    58: ["শরীয়তপুর সদর", "ডামুড্যা", "নড়িয়া", "জাজিরা", "ভেদরগঞ্জ", "গোসাইরহাট"],
    59: ["শেরপুর সদর", "নালিতাবাড়ী", "ঝিনাইগাতী", "নকলা", "শ্রীবরদী"],
    60: ["সাতক্ষীরা সদর", "কলারোয়া", "তালা", "আশাশুনি", "শ্যামনগর", "কালীগঞ্জ", "দেবহাটা"],
    61: ["সিরাজগঞ্জ সদর", "বেলকুচি", "চৌহালী", "কামারখন্দ", "কাজীপুর", "রায়গঞ্জ", "শাহজাদপুর", "তাড়াশ", "উল্লাপাড়া"],
    62: ["সিলেট সদর", "বিয়ানীবাজার", "গোলাপগঞ্জ", "ফেঞ্চুগঞ্জ", "বালাগঞ্জ", "বিশ্বনাথ", "কোম্পানীগঞ্জ", "গৌরীপুর", "জৈন্তাপুর", "কানাইঘাট", "জকিগঞ্জ", "দক্ষিণ সুরমা", "ওসমানীনগর"],
    63: ["সুনামগঞ্জ সদর", "ছাতক", "জগন্নাথপুর", "দিরাই", "শাল্লা", "ধর্মপাশা", "তাহিরপুর", "বিশ্বম্ভরপুর", "দোয়ারাবাজার", "জামালগঞ্জ", "মধ্যনগর"],
    64: ["হবিগঞ্জ সদর", "নবীগঞ্জ", "বাহুবল", "আজমিরীগঞ্জ", "বানিয়াচং", "লাখাই", "চুনারুঘাট", "মাধবপুর", "শায়েস্তাগঞ্জ"]    
}

export const upazilasEn: { [key: number]: string[] } = {
  1: ["Cox's Bazar Sadar", "Ukhiya", "Teknaf", "Ramu", "Chakaria", "Moheshkhali", "Pekua", "Kutubdia", "Eidgaon"],
  2: ["Kishoreganj Sadar", "Karimganj", "Tarail", "Hossainpur", "Kotiadi", "Kuliarchar", "Bhairab", "Nikli", "Bajitpur", "Itna", "Mithamain", "Austagram", "Pakundia"],
  3: ["Cumilla Sadar", "Laksam", "Debidwar", "Muradnagar", "Daudkandi", "Chauddagram", "Barura", "Burichang", "Brahmanpara", "Chandina", "Homna", "Langalkot", "Meghna", "Monohargonj", "Titas", "Sadar South"],
  4: ["Kushtia Sadar", "Kumarkhali", "Khoksa", "Mirpur", "Daulatpur", "Bheramara"],
  5: ["Kurigram Sadar", "Ulipur", "Chilmari", "Rhumari", "Char Rajibpur", "Nageshwari", "Bhurungamari", "Rajarhat", "Kurigram Phulbari"],
  6: ["Khagrachhari Sadar", "Dighinala", "Panchhari", "Matiranga", "Mahalchhari", "Manikchhari", "Ramgarh", "Lakshmichhari", "Guimara"],
  7: ["Khulna Sadar", "Koyra", "Dumuria", "Terkhada", "Dacope", "Dighalia", "Paikgacha", "Phultala", "Batiaghata", "Rupsha"],
  8: ["Gaibandha Sadar", "Sadullapur", "Palashbari", "Sundarganj", "Saghata", "Gobindaganj", "Fulchhari"],
  9: ["Gazipur Sadar", "Kaliakair", "Kaliganj", "Kapasia", "Sreepur"],
  10: ["Gopalganj Sadar", "Kotalipara", "Tungipara", "Kashiani", "Muksudpur"],
  11: ["Chittagong City", "Anwara Upazila sadar", "Banshkhali Upazila sadar", "Boalkhali Upazila Sadar", "Chandanaish Upazila Sadar", "Fatikchhari Upazila Sadar", "Hathazari Upazila Sadar", "Lohagara Upazila Sadar (CTG)", "Mirsharai", "Patiya Upazila Sadar", 
  "Rangunia Upazila Sadar", "Raozan Upazila Sadar", "Satkania Upazila Sadar", "Sitakund", "Cornel Hat (Chittagong)", "Potenga chittagong", "Chittagong University of Engineering & Technology (CUET)", "Oxyzen Mor", "Halishohor", "AK Khan", 
  "Pahartoli", "Akbor Shah", "Chittagong EPZ", "Agrabad", "Chittagong New market", "Andarkilla", "Chowkbazar", "Sadarghat", "GEC Mor", "Khulshi", 
  "2 no gate", "Panchlaish", "Bayzid Bostami", "Noyabazar", "Kodomtoli", "Dewanhat", "Sagorika", "Alonkar", "Foy's Lake", "Muradpur", 
  "Aturar Depot", "Bakoliya", "Mirjarpol", "Boddarhat", "Madarbari", "SK Mujib Road", "Chowmohoni", "Double Mooring", "Asadganj", "Khatunganj", 
  "Hathazari", "Chandgaon", "Kotwali", "Raozan", "Satkania", "Anowara", "Banshkhali", "Karnaphuli", "Boalkhali", "Chandanaish", 
  "Patiya", "Chittagong Port", "Double Mooring", "Patenga", "Bayejid Bostami", "Bakalia", "Bhujpur", "Chowdhury Hat", "Rangunia", "Sitakunda", 
  "Fatikchhari", "Mirsharai", "Sandwip", "Lalkhan Bazar", "Garibullah Shah Mazar", "Dampara", "Jonota Colony", "Monsurabad", "Jhautola", "Nasirabad", 
  "Shugandha Residential", "Sholoshahor", "Rose Vally R/A", "Oxygen", "CTG Cantonment", "Mehedibag", "Kajir Dewri", "Jamalkhan", "EPZ", "Firingi Bazar", 
  "Pathar Ghata", "Paroikora", "Paroikora", "Al- Amin Baria Madra", "Gachbaria", "East Joara", "Barma", "Dohazari", "Ramghar Head Office", "Harualchhari", 
  "Najirhat", "Jarachhari", "Kalipur", "Kalipur", "Gorakghat", "Longachh", "Marishya", "Barakal", "Padua", "Anandabazar", 
  "jagannath Hat", "B.I.T Post Office", "Fatepur", "Beenajuri", "Gahira", "Kundeshwari", "Mohamuni", "Dewanpur", "Rampura", "Chitt. Politechnic In", 
  "Middle Patenga", "Jaldia Merine Accade", "North Katuli", "Chitt. Sailers Colon", "Chittagong Airport", "North Halishahar", "Chittagong Airport", "North Halishahar", "Khan Bahadur", "Gunagari", 
  "Jaldia Merine Accade", "Banigram", "Yunus Nagar", "Fatahabad", "Gorduara", "Katirhat", "Madrasa", "Nuralibari", "Rajsthali", "Kanungopara", 
  "Saroatoli", "Iqbal Park", "Baitul Ijjat", "Betbunia", "Kalampati", "Nanichhar", "Ward No-15", "Ward No-16 (Part)", "Ward No-20", "Ward No-21", 
  "Ward No-22", "Ward No-31", "Ward No-32", "Ward No-33", "Ward No-34", "Ward No-35 (Part)", "Ward No-17", "Ward No-18", "Ward No-19", "Ward No-35 (Part)", 
  "Ward No-04", "Ward No-05", "Ward No-06", "Ward No-37", "Ward No-38", "Ward No-39", "Ward No-23", "Ward No-24 (Part)", "Ward No-27", "Ward No-27", 
  "Ward No-28", "Ward No-29", "Ward No-30", "Ward No-36", "Ward No-24(Part)", "Ward No-11 (Part)", "Ward No-25", "Ward No-26", "Ward No-08(Part)", "Ward No-09", 
  "Ward No-13", "Ward No-14", "Ward No-10", "Ward No-12", "Ward No-08(Part)", "Ward No-07", "Ward No-16 (Part)", "Halishohor", "EPZ", "Halishohor", 
  "EPZ", "Wajediya", "baluchora", "ranirhat"],
  12: ["Chandpur Sadar", "Haziganj", "Kachua", "Faridganj", "Matlab North", "Matlab South", "Haimchar", "Shahrasti"],
  13: ["Chapainawabganj Sadar", "Shibganj", "Gomastapur", "Nachole", "Volahat"],
  14: ["Chuadanga Sadar", "Alamdanga", "Damurhuda", "Jibannagar"],
  15: ["Jamalpur Sadar", "Melandah", "Islampur", "Dewanganj", "Sarishabari", "Madarganj", "Bakshiganj"],
  16: ["Joypurhat Sadar", "Panchbibi", "Akkelpur", "Kalai", "Khetlal"],
  17: ["Jhalokati Sadar", "Nalchity", "Rajapur", "Kathalia"],
  18: ["Jhenaidah Sadar", "Shailkupa", "Harinakundu", "Kaliganj", "Kotchandpur", "Moheshpur"],
  19: ["Tangail Sadar", "Kalihati", "Ghatail", "Basail", "Gopalpur", "Mirzapur", "Nagarpur", "Madhupur", "Sakhipur", "Delduar", "Dhanbari", "Bhuapur"],
  20: ["Thakurgaon Sadar", "Pirganj", "Baliadangi", "Ranisankail", "Haripur"],
  
  21: ["Savar", "Ashulia", "Hemayetpur", "Nabinagar", "Dhamrai", "Keraniganj", "Zinzira", "Nawabganj", "Dohar", "Amin Bazar",
  "Mirpur 1", "Mirpur 2", "Mirpur 10", "Mirpur 11", "Mirpur 12", "Mirpur 13", "Mirpur 14", "Mirpur DOHS", "Mirpur 60 Feet", "Shewrapara",
  "Kazipara", "Pallabi", "Rupnagar", "Shah Ali", "Kafrul", "Agargaon", "Taltola", "Kallayanpur", "Darus Salam", "Gabtoli",
  "Uttara Sector 1-10", "Uttara Sector 11-18", "Abdullahpur", "Uttar Khan", "Dakkhin Khan", "Airport Area", "Ashkona", "Khilket", "Nikunjo", "Kuril",
  "Bashundhara RA", "Baridhara RA", "Baridhara DOHS", "Norda", "Vatara", "Badda", "Merul Badda", "Shahjadpur", "Satarkul", "Purbachal 300 Feet",
  "Gulshan 1", "Gulshan 2", "Banani", "Banani DOHS", "Mohakhali", "Mohakhali DOHS", "Niketon", "Tejgaon", "Tejgaon Industrial Area", "Kawran Bazar",
  "Farmgate", "Panthapath", "Green Road", "Hatirpool", "Dhanmondi", "Sobhanbag", "Kalabagan", "Kathalbagan", "Science Lab", "Elephant Road",
  "Mohammadpur", "Adabor", "Shekertek", "Shia Masjid", "Bosila", "Dhaka Uddan", "Lalmatia", "Rayerbazar", "Zigatola", "Hazaribagh",
  "Lalbagh", "Chawkbazar", "Kotwali", "Babu Bazar", "Nawabpur", "Sodorghat", "Sutrapur", "Gendaria", "Wari", "Tikatuli",
  "Jatrabari", "Shonir Akhra", "Rayerbagh", "Matuail", "Donia", "Demra", "Shyampur", "Kamrangirchor", "Postogola", "Jurain",
  "Sabujbagh", "Bashabo", "Khilgaon", "Goran", "Rampura", "Banasree", "Aftabnagar", "Malibagh", "Mouchak", "Moghbazar",
  "Siddheswari", "Bailey Road", "Shantinagar", "Kakrail", "Paltan", "Motijheel", "Dilkusha", "Komlapur", "Shahjahanpur", "Mugda",
  "Sayedabad", "Romna", "Shahbagh", "Dhaka University Area", "New Market", "Azimpur", "Nilkhet", "Bakshibazar", "Segunbagicha", "Dhaka Cantonment"],

  22: ["Dinajpur Sadar", "Birampur", "Nawabganj", "Birganj", "Bochaganj", "Chirirbandar", "Phulbari", "Kaharole", "Khansama", "Parbatipur", "Hakimpur", "Ghoraghat"],
  23: ["Naogaon Sadar", "Patnitala", "Dhamoirhat", "Mahadebpur", "Porsha", "Sapahar", "Badalgachhi", "Atrai", "Raninagar", "Niamatpur", "Manda"],
  24: ["Narsingdi Sadar", "Palash", "Shibpur", "Monohardi", "Belabo", "Raipura"],
  25: ["Natore Sadar", "Bagatipara", "Baraigram", "Gurudaspur", "Lalpur", "Singra", "Naldanga"],
  26: ["Narayanganj Sadar", "Bandar", "Araihazar", "Rupganj", "Sonargaon"],
  27: ["Nilphamari Sadar", "Sayedpur", "Jaldhaka", "Kishoreganj", "Domar", "Dimla"],
  28: ["Netrokona Sadar", "Barhatta", "Kalamakanda", "Durgapur", "Kendua", "Madan", "Mohanganj", "Purbadhala", "Khaliajuri", "Atpara"],
  29: ["Noakhali Sadar", "Companiganj", "Begumganj", "Chatkhil", "Senbagh", "Hatiya", "Subarnachar", "Sonaimuri", "Kabirhat"],
  30: ["Narail Sadar", "Lohagara", "Kalia"],

  31: ["Panchagarh Sadar", "Tetulia", "Boda", "Debiganj", "Atwari"],
  32: ["Patuakhali Sadar", "Bauphal", "Galachipa", "Dashmina", "Mirzaganj", "Kalapara", "Dumki", "Rangabali"],
  33: ["Pabna Sadar", "Ishwardi", "Bhangura", "Chatmohar", "Faridpur", "Sujanagar", "Bera", "Atgharia", "Santhia"],
  34: ["Pirojpur Sadar", "Nazirpur", "Nesarabad", "Kawkhali", "Bhandaria", "Mathbaria", "Indurkani"],
  35: ["Faridpur Sadar", "Alfadanga", "Boalmari", "Sadorpur", "Nagarkanda", "Bhanga", "Charbhadrasan", "Madhukhali", "Saltha"],
  36: ["Feni Sadar", "Chhagalnaiya", "Parshuram", "Fulgazi", "Daganbhuiyan", "Sonagazi"],
  37: ["Bogra Sadar", "Shajahanpur", "Sherpur", "Dhunat", "Nandigram", "Kahalu", "Adamdighi", "Dupchanchia", "Shibganj", "Sonatala", "Gabtoli", "Sariakandi"],
  38: ["Barguna Sadar", "Amtali", "Patharghata", "Bamna", "Betagi", "Taltali"],
  39: ["Barishal Sadar", "Bakerganj", "Babuganj", "Wazirpur", "Banaripara", "Gournadi", "Agailjhara", "Muladi", "Mehendiganj", "Hizla"],
  40: ["Bagerhat Sadar", "Fakirhat", "Mollahat", "Chitalmari", "Kachua", "Rampal", "Mongla", "Sarankhola", "Morrelganj"],
  
  41: ["Bandarban Sadar", "Ruma", "Thanchi", "Rowangchhari", "Lama", "Alikadam", "Naikhongchhari"],
  42: ["Brahmanbaria Sadar", "Kasba", "Nasirnagar", "Sarail", "Ashuganj", "Akhaura", "Nabinnagar", "Bancharampur", "Bijoynagar"],
  43: ["Bhola Sadar", "Borhanuddin", "Char Fasson", "Lalmohan", "Tazumuddin", "Daulatkhan", "Manpura"],
  44: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
  45: ["Madaripur Sadar", "Shibchar", "Kalkini", "Rajoir", "Dasar"],
  46: ["Manikganj Sadar", "Singair", "Ghior", "Saturia", "Harirampur", "Shibalaya", "Daulatpur"],
  47: ["Munshiganj Sadar", "Sreenagar", "Sirajdikhan", "Louhajang", "Tongibari", "Gajaria"],
  48: ["Meherpur Sadar", "Gangni", "Mujibnagar"],
  49: ["Moulvibazar Sadar", "Sreemangal", "Rajnagar", "Kulaura", "Barlekha", "Kamalganj", "Juri"],
  50: ["Mymensingh Sadar", "Muktagachha", "Fulbaria", "Trishal", "Bhaluka", "Gafargaon", "Ishwarganj", "Nandail", "Gauripur", "Phulpur", "Dhobaura", "Haluaghat", "Tarakanda"],
  
  51: ["Jashore Sadar", "Jhikargachha", "Sharsha", "Chougachha", "Keshabpur", "Manirampur", "Abhaynagar", "Bagherpara"],
  52: ["Rangpur Sadar", "Mithapukur", "Pirganj", "Pirgachha", "Kaunia", "Gangachhara", "Badarganj", "Tapadhan"],
  53: ["Rangamati Sadar", "Kaptai", "Kawkhali", "Baghaichhari", "Langadu", "Naniarchar", "Rajasthali", "Jurachhari", "Barkal", "Bilaichhari"],
  54: ["Rajbari Sadar", "Goalanda", "Pangsha", "Baliakandi", "Kalukhali"],
  55: ["Rajshahi Sadar", "Paba", "Tanore", "Godagari", "Mohanpur", "Bagmara", "Durgapur", "Puthia", "Charghat", "Bagha"],
  56: ["Lakshmipur Sadar", "Raipur", "Ramganj", "Ramgati", "Kamalnagar"],
  57: ["Lalmonirhat Sadar", "Kaliganj", "Hatibandha", "Patgram", "Aditmari"],
  58: ["Shariatpur Sadar", "Damudya", "Naria", "Zajira", "Bhederganj", "Gosairhat"],
  59: ["Sherpur Sadar", "Nalitabari", "Jhenaigati", "Nakla", "Sreebardi"],
  60: ["Satkhira Sadar", "Kalaroa", "Tala", "Ashashuni", "Shyamnagar", "Kaliganj", "Debhata"],
  61: ["Sirajganj Sadar", "Belkuchi", "Chauhali", "Kamarkhanda", "Kazipur", "Rayganj", "Shahzadpur", "Tarash", "Ullapara"],
  62: ["Sylhet Sadar", "Beanibazar", "Golapganj", "Fenchuganj", "Balaganj", "Biswanath", "Companiganj", "Gauripur", "Jaintiapur", "Kanaighat", "Zakiganj", "South Surma", "Osmaninagar"],
  63: ["Sunamganj Sadar", "Chhatak", "Jagannathpur", "Derai", "Shalla", "Dharampasha", "Tahirpur", "Bishwamavpur", "Dowarabazar", "Jamalganj", "Madhyanagar"],
  64: ["Habiganj Sadar", "Nabiganj", "Bahubal", "Azmiriganj", "Baniachachong", "Lakhai", "Chunarughat", "Madhabpur", "Shayestaganj"]
};