export const districts = [

    { "id": 1, "name": "কক্সবাজার", "en_name": "Cox's Bazar" },
    { "id": 2, "name": "কিশোরগঞ্জ", "en_name": "Kishoreganj" },
    { "id": 3, "name": "কুমিল্লা", "en_name": "Cumilla" },
    { "id": 4, "name": "কুষ্টিয়া", "en_name": "Kushtia" },
    { "id": 5, "name": "কুড়িগ্রাম", "en_name": "Kurigram" },
    { "id": 6, "name": "খাগড়াছড়ি", "en_name": "Khagrachhari" },
    { "id": 7, "name": "খুলনা", "en_name": "Khulna" },
    { "id": 8, "name": "গাইবান্ধা", "en_name": "Gaibandha" },
    { "id": 9, "name": "গাজীপুর", "en_name": "Gazipur" },
    { "id": 10, "name": "গোপালগঞ্জ", "en_name": "Gopalganj" },
    { "id": 11, "name": "চট্টগ্রাম", "en_name": "Chattogram" },
    { "id": 12, "name": "চাঁদপুর", "en_name": "Chandpur" },
    { "id": 13, "name": "চাঁপাইনবাবগঞ্জ", "en_name": "Chapainawabganj" },
    { "id": 14, "name": "চুয়াডাঙ্গা", "en_name": "Chuadanga" },
    { "id": 15, "name": "জামালপুর", "en_name": "Jamalpur" },
    { "id": 16, "name": "জয়পুরহাট", "en_name": "Joypurhat" },
    { "id": 17, "name": "ঝালকাঠি", "en_name": "Jhalokati" },
    { "id": 18, "name": "ঝিনাইদহ", "en_name": "Jhenaidah" },
    { "id": 19, "name": "টাঙ্গাইল", "en_name": "Tangail" },
    { "id": 20, "name": "ঠাকুরগাঁও", "en_name": "Thakurgaon" },
    { "id": 21, "name": "ঢাকা", "en_name": "Dhaka" },
    { "id": 22, "name": "দিনাজপুর", "en_name": "Dinajpur" },
    { "id": 23, "name": "নওগাঁ", "en_name": "Naogaon" },
    { "id": 24, "name": "নরসিংদী", "en_name": "Narsingdi" },
    { "id": 25, "name": "নাটোর", "en_name": "Natore" },
    { "id": 26, "name": "নারায়ণগঞ্জ", "en_name": "Narayanganj" },
    { "id": 27, "name": "নীলফামারী", "en_name": "Nilphamari" },
    { "id": 28, "name": "নেত্রকোনা", "en_name": "Netrokona" },
    { "id": 29, "name": "নোয়াখালী", "en_name": "Noakhali" },
    { "id": 30, "name": "নড়াইল", "en_name": "Narail" },
    { "id": 31, "name": "পঞ্চগড়", "en_name": "Panchagarh" },
    { "id": 32, "name": "পটুয়াখালী", "en_name": "Patuakhali" },
    { "id": 33, "name": "পাবনা", "en_name": "Pabna" },
    { "id": 34, "name": "পিরোজপুর", "en_name": "Pirojpur" },
    { "id": 35, "name": "ফরিদপুর", "en_name": "Faridpur" },
    { "id": 36, "name": "ফেনী", "en_name": "Feni" },
    { "id": 37, "name": "বগুড়া", "en_name": "Bogra" },
    { "id": 38, "name": "বরগুনা", "en_name": "Barguna" },
    { "id": 39, "name": "বরিশাল", "en_name": "Barishal" },
    { "id": 40, "name": "বাগেরহাট", "en_name": "Bagerhat" },
    { "id": 41, "name": "বান্দরবান", "en_name": "Bandarban" },
    { "id": 42, "name": "ব্রাহ্মণবাড়িয়া", "en_name": "Brahmanbaria" },
    { "id": 43, "name": "ভোলা", "en_name": "Bhola" },
    { "id": 44, "name": "মাগুরা", "en_name": "Magura" },
    { "id": 45, "name": "মাদারীপুর", "en_name": "Madaripur" },
    { "id": 46, "name": "মানিকগঞ্জ", "en_name": "Manikganj" },
    { "id": 47, "name": "মুন্সিগঞ্জ", "en_name": "Munshiganj" },
    { "id": 48, "name": "মেহেরপুর", "en_name": "Meherpur" },
    { "id": 49, "name": "মৌলভীবাজার", "en_name": "Moulvibazar" },
    { "id": 50, "name": "ময়মনসিংহ", "en_name": "Mymensingh" },
    { "id": 51, "name": "যশোর", "en_name": "Jashore" },
    { "id": 52, "name": "রংপুর", "en_name": "Rangpur" },
    { "id": 53, "name": "রাঙামাটি", "en_name": "Rangamati" },
    { "id": 54, "name": "রাজবাড়ী", "en_name": "Rajbari" },
    { "id": 55, "name": "রাজশাহী", "en_name": "Rajshahi" },
    { "id": 56, "name": "লক্ষ্মীপুর", "en_name": "Lakshmipur" },
    { "id": 57, "name": "লালমনিরহাট", "en_name": "Lalmonirhat" },
    { "id": 58, "name": "শরীয়তপুর", "en_name": "Shariatpur" },
    { "id": 59, "name": "শেরপুর", "en_name": "Sherpur" },
    { "id": 60, "name": "সাতক্ষীরা", "en_name": "Satkhira" },
    { "id": 61, "name": "সিরাজগঞ্জ", "en_name": "Sirajganj" },
    { "id": 62, "name": "সিলেট", "en_name": "Sylhet" },
    { "id": 63, "name": "সুনামগঞ্জ", "en_name": "Sunamganj" },
    { "id": 64, "name": "হবিগঞ্জ", "en_name": "Habiganj" }
  ]
  

  export const upazilas: { [key: number]: string[] } = {
    1: ["কক্সবাজার সদর", "উখিয়া", "টেকনাফ", "রামু", "চকরিয়া", "মহেশখালী", "পেকুয়া", "কুতুবদিয়া", "ঈদগাঁও"],
    2: ["কিশোরগঞ্জ সদর", "করিমগঞ্জ", "তাড়াইল", "হোসেনপুর", "কটিয়াদী", "কুলিয়ারচর", "ভৈরব", "নিকলী", "বাজিতপুর", "ইটনা", "মিঠামইন", "অষ্টগ্রাম", "পাকুন্দিয়া"],
    3: ["কুমিল্লা সদর", "লাকসাম", "দেবিদ্বার", "মুরাদনগর", "দাউদকান্দি", "চৌদ্দগ্রাম", "বরুড়া", "বুড়িচং", "ব্রাহ্মণপাড়া", "চাঁন্দিনা", "হোমনা", "লাঙ্গলকোট", "মেঘনা", "মনোহরগঞ্জ", "তিতাস", "সদর দক্ষিণ"],
    4: ["কুষ্টিয়া সদর", "কুমারখালী", "খোকসা", "মিরপুর", "দৌলতপুর", "ভেড়ামারা"],
    5: ["কুড়িগ্রাম সদর", "উলিপুর", "চিলমারী", "রুমারী", "চর রাজিবপুর", "নাগেশ্বরী", "ভুরুঙ্গামারী", "রাজারহাট", " কুড়িগ্রাম ফুলবাড়ী"],
    6: ["খাগড়াছড়ি সদর", "দিঘীনালা", "পানছড়ি", "মাটিরাঙ্গা", "মহালছড়ি", "মানিকছড়ি", "রামগড়", "লক্ষ্মীছড়ি", "গুইমারা"],
    7: ["খুলনা সদর", "কয়রা", "ডুমুরিয়া", "তেরখাদা", "দাকোপ", "দিঘলিয়া", "পাইকগাছা", "ফুলতলা", "বটিয়াঘাটা", "রূপসা"],
    8: ["গাইবান্ধা সদর", "সাদুল্লাপুর", "পলাশবাড়ী", "সুন্দরগঞ্জ", "সাঘাটা", "গোবিন্দগঞ্জ", "ফুলছড়ি"],
    9: ["গাজীপুর সদর", "কালিয়াকৈর", "কালীগঞ্জ", "কপাসিয়া", "শ্রীপুর"],
    10: ["গোপালগঞ্জ সদর", "কোটালীপাড়া", "টুঙ্গিপাড়া", "কাশিয়ানী", "مুকসুদপুর"],
    11: ["চট্টগ্রাম সদর", "পটিয়া", "আনোয়ারা", "চন্দনাইশ", "বাঁশখালী", "বোয়ালখালী", "রাঙ্গুনিয়া", "রাউজান", "হাটহাজারী", "মিরসরাই", "সীতাকুণ্ড", "ফটিকছড়ি", "সন্দীপ", "সাতকানিয়া", "লোহাগাড়া"],
    12: ["চাঁদপুর সদর", "হাজীগঞ্জ", "কচুয়া", "ফরিদগঞ্জ", "মতলব উত্তর", "মতলব দক্ষিণ", "হাইমচর", "শাহরাস্তি"],
    13: ["চাঁপাইনবাবগঞ্জ সদর", "শিবগঞ্জ", "গোমস্তাপুর", "নাচোল", "ভোলাহাট"],
    14: ["চুয়াডাঙ্গা সদর", "আলমডাঙ্গা", "দামুড়হুদা", "জীবননগর"],
    15: ["জামালপুর সদর", "মেলান্দহ", "ইসলামপুর", "দেওয়ানগঞ্জ", "সরিষাবাড়ী", "মাদারগঞ্জ", "বকশীগঞ্জ"],
    16: ["জয়পুরহাট সদর", "পাঁচবিবি", "আক্কেলপুর", "কালাই", "ক্ষেতলাল"],
    17: ["ঝালকাঠি সদর", "নলছিটি", "রাজাপুর", "কাঠালিয়া"],
    18: ["ঝিনাইদহ সদর", "শৈলকুপা", "হরিণাকুণ্ডু", "কালীগঞ্জ", "কোটচাঁদপুর", "মহেশপুর"],
    19: ["টাঙ্গাইল সদর", "কালিহাতী", "ঘাটাইল", "বাসাইল", "গোপালপুর", "মির্জাপুর", "নাগরপুর", "مধুপুর", "সখিপুর", "দেলদুয়ার", "ধনবাড়ী", "ভূঞাপুর"],
    20: ["ঠাকুরগাঁও সদর", "পীরগঞ্জ", "বালীয়াডাঙ্গী", "রাণীশংকৈল", "হরিপুর"],
    
    21: ["সাভার", "আশুলিয়া", "হেমায়েতপুর", "নবীনগর", "ধামরাই", "কেরানীগঞ্জ", "কদমতলী (কেরানীগঞ্জ)", "জিঞ্জিরা", "নবাবগঞ্জ", "দোহার", "মিরপুর-১", "মিরপুর-২", "মিরপুর-১০", "মিরপুর-১১", "মিরপুর-১২", "মিরপুর-১৩", "মিরপুর-১৪", "মিরপুর ডিওএইচএস (DOHS)", "মিরপুর-৬০ ফিট", "শেওড়াপাড়া", "কাজীপাড়া", "পল্লবী", "রূপনগর", "শাহ আলী", "কাফরুল", "আগারগাঁও", "তালতলা", "উত্তরা সেক্টর-১ থেকে ১০", "উত্তরা সেক্টর-১১ থেকে ১৮", "উত্তরা মডেল টাউন", "দিয়াবাড়ী", "আব্দুল্লাহপুর", "উত্তরাখান", "দক্ষিণখান", "ফায়দাবাদ", "বিমানবন্দর এলাকা", "খিলক্ষেত", "নিকুঞ্জ-১", "নিকুঞ্জ-২", "কুড়িল", "কুড়াতলী", "জোয়ার সাহারা", "বসুন্ধরা আবাসিক এলাকা", "বারিধারা আবাসিক এলাকা", "বারিধারা ডিওএইচএস (DOHS)", "নদ্দা", "কালাচাঁদপুর", "গুলশান-১", "গুলশান-২", "বনানী", "বনানী ডিওএইচএস (DOHS)", "মহাখালী", "مহাখালী ডিওএইচএস (DOHS)", "নিকেতন", "তেজগাঁও", "তেজগাঁও শিল্প এলাকা", "কারওয়ান বাজার", "ফার্মগেট", "রাজাবাজার", "ইন্দিরা রোড", "ধানমন্ডি", "কলাবাগান", "কাঠালবাগান", "গ্রিন রোড", "সেন্ট্রাল রোড", "মোহাম্মদপুর", "জাপান গার্ডেন宿", "শিয়া মসজিদ", "আদাবর", "শেখেরটেক", "ঢাকা উদ্যান", "বছিলা", "হাজারীবাগ", "জিগাতলা", "লালমাটিয়া", "রায়েরবাজার", "লালবাগ", "চকবাজার", "ইসলামপুর", "কোতোয়ালী", "বাবু বাজার", "নবাবপুর", "সদরঘাট", "সূত্রাপুর", "গেন্ডারিয়া", "ওয়ারী", "টিপু সুলতান রোড", "যাত্রাবাড়ী", "ধলপুর", "শনির আখড়া", "রায়েরবাগ", "মাতুয়াইল", "দния", "ডেমরা", "শ্যামপুর", "কদমতলী", "সবুজবাগ", "বাসাবো", "খিলগাঁও", "সিপাহীবাগ", "গোড়ান", "রামপুরা", "বনশ্রী", "আফতাবনগর", "মালিবাগ", "مৌচাক", "مগবাজার", "সিদ্ধেশ্বরী", "বেইলি রোড", "শান্তিনগর", "কাকরাইল", "পল্টন", "মতিঝিল", "দিলকুশা", "কমলাপুর", "শাহজাহানপুর", "মুগদা", "মান্ডা", "মানিকনগর", "সায়দাবাদ", "রমনা", "শাহবাগ", "ঢাকা বিশ্ববিদ্যালয় এলাকা", "নিউমার্কেট", "আজিমপুর", "নীলক্ষেত", "বক্সিবাজার", "সেগুনবাগিচা", "তোপখানা রোড", "হাতিরঝিল", "বাড্ডা", "উত্তর বাড্ডা", "দক্ষিণ বাড্ডা", "মধ্য বাড্ডা", "মেরুল বাড্ডা", "শাহজাদপুর", "ভাটারা", "সাতারকুল", "বেরাইদ", "কামরাঙ্গীরচর", "ভাষানটেক", "মানিকদি", "মাটিকাটা", "ঢাকা সেনানিবাস (Cantonment)"],

    22: ["দিনাজপুর সদর", "বিরামপুর", "নবাবগঞ্জ", "বীরগঞ্জ", "বোচাগঞ্জ","চিরিরবন্দর", "ফুলবাড়ী", "কাহারোল", "খানসামা", "পার্বতীপুর", "হাকিমপুর", "ঘোড়াঘাট"],
    23: ["নওগাঁ সদর", "পত্নীতলা", "ধামইরহাট", "মহাদেবপুর", "পোরশা", "সাপাহার", "বদলগাছী", "আত্রাই", "রানীনগর", "নিয়ামতপুর", "মান্দা"],
    24: ["নরসিংদী সদর", "পলাশ", "শিবপুর", "মনোহরদী", "বেলাবো", "রায়পুরা"],
    25: ["নাটোর সদর", "বাগাতিপাড়া", "বড়াইগ্রাম", "গুরুদাসপুর", "লালপুর", "সিংড়া", "নলডাঙ্গা"],
    26: ["নারায়ণগঞ্জ সদর", "বন্দর", "আড়াইহাজার", "রূপগঞ্জ", "সোনারগাঁও"],
    27: ["নীলফামারী সদর", "সৈয়দপুর", "জলঢাকা", "কিশোরগঞ্জ", "ডোমার", "ডিমলা"],
    28: ["নেত্রকোনা সদর", "বারহাট্টা", "কলমাকান্দা", "দুর্গাপুর", "কেন্দুয়া", "মদন", "মোহনগঞ্জ", "পূর্বধলা", "খালিয়াজুরী", "আটপাড়া"],
    29: ["নোয়াখালী সদর", "কোম্পানীগঞ্জ", "বেগমগঞ্জ", "চাটখিল", "সেনবাগ", "হাতিয়া", "সুবর্ণচর", "সোনাইমুড়ী", "কবিরহাট"],
    30: ["নড়াইল সদর", "লোহাগড়া", "কালিয়া"],

    31: ["পঞ্চগড় সদর", "তেঁতুলিয়া", "বোদা", "দেবীগঞ্জ", "আটোয়ারী"],
    32: ["পটুয়াখালী সদর", "বাউফল", "গলাচিপা", "দশমিনা", "মির্জাগঞ্জ", "কলাপাড়া", "দুমকি", "রাঙ্গাবালী"],
    33: ["পাবনা সদর", "ঈশ্বরদী", "ভাঙ্গুড়া", "চাটমোহর", "ফরিদপুর", "সুজানগর", "বেড়া", "আটঘরিয়া", "সাথিয়া"],
    34: ["পিরোজপুর সদর", "নাজিরপুর", "নেছারাবাদ", "কাওখালী", "ভাণ্ডারিয়া", "মঠবাড়িয়া", "ইন্দুরকানী"],
    35: ["ফরিদপুর সদর", "আলফাডাঙ্গা", "বোয়ালমারী", "সদরপুর", "নগরকান্দা", "ভাঙ্গা", "চরভদ্রাসন", "মধুখালী", "সালথা"],
    36: ["ফেনী সদর", "ছাগলনাইয়া", "পরশুরাম", "ফুলগাজী", "দাগনভূঁইয়া", "সোনাগাজী"],
    37: ["বগুড়া সদর", "শাজাহানপুর", "শেরপুর", "ধুনট", "নন্দীগ্রাম", "কাহালু", "আদমদিঘী", "দুপচাঁচিয়া", "শিবগঞ্জ", "সোনাতলা", "গাবতলী", "সারিয়াকান্দি"],
    38: ["বরগুনা সদর", "আমতলী", "পাথরঘাটা", "বামনা", "বেতাগী", "তালতলী"],
    39: ["বরিশাল সদর", "বাকেরগঞ্জ", "বাবুগঞ্জ", "উজিরপুর", "বানারীপাড়া", "গৌরনদী", "আগৈলঝারা", "মুলাদী", "হিজলা", "মেহেন্দিগঞ্জ"],
    40: ["বাগেরহাট সদর", "ফকিরহাট", "মোল্লাহাট", "চিতলমারী", "কচুয়া", "রামপাল", "মোংলা", "শরণখোলা", "মোড়েলগঞ্জ"],
    
    41: ["বান্দরবান সদর", "রুমা", "থানচি", "রোয়াংছড়ি", "লামা", "আলীকদম", "নাইক্ষ্যংছড়ি"],
    42: ["ব্রাহ্মণবাড়িয়া সদর", "কসবা", "নাসিরনগর", "সরাইল", "আশুগঞ্জ", "আখাউড়া", "নবীনগর", "বাঞ্ছারামপুর", "বিজয়নগর"],
    43: ["ভোলা সদর", "বোরহানউদ্দিন", "চরফ্যাশন", "লালমোহন", "তজুমদ্দিন", "দৌলতখান", "মনপুরা"],
    44: ["মাগুরা সদর", "মহম্মদপুর", "শালিখা", "শ্রীপুর"],
    45: ["মাদারীপুর সদর", "শিবচর", "কালকিনি", "রাজৈর", "ডাসার"],
    46: ["মানিকগঞ্জ সদর", "সিংগাইর", "ঘিওর", "সাটুরিয়া", "হরিরামপুর", "শিবালয়", "দৌলতপুর"],
    47: ["মুন্সিগঞ্জ সদর", "শ্রীনগর", "সিরাজদিখান", "লৌহজং", "টংগিবাড়ী", "গজারিয়া"],
    48: ["মেহেরপুর সদর", "গাংনী", "মুজিবনগর"],
    49: ["মৌলভীবাজার সদর", "শ্রীমঙ্গল", "রাজনগর", "কুলাউড়া", "বড়লেখা", "কমলগঞ্জ", "জুড়ী"],
    50: ["ময়মনসিংহ সদর", "মুক্তাগাছা", "ফুলবাড়ীয়া", "ত্রিশাল", "ভালুকা", "গফরগাঁও", "ঈশ্বরগঞ্জ", "নান্দাইল", "গৌরীপুর", "ফুলপুর", "ধোবাউড়া", "হালুয়াঘাট", "তারাকান্দা"],
    
    51: ["যশোর সদর", "ঝিকরগাছা", "শার্শা", "চৌগাছা", "কেশবপুর", "মণিরামপুর", "অভয়নগর", "বাঘেরপাড়া"],
    52: ["রংপুর সদর", "মিঠাপুকুর", "পীরগঞ্জ", "পীরগাছা", "কাউনিয়া", "গঙ্গাচড়া", "বদরগঞ্জ", "তপাধন"],
    53: ["রাঙামাটি সদর", "কাপ্তাই", "কাউখালী", "বাঘাইছড়ি", "লংগদু", "নানিয়ারচর", "রাজস্থলী", "জুরাছড়ি", "বরকল", "বিলাইছড়ি"],
    54: ["রাজবাড়ী সদর", "গোয়ালন্দ", "পাংশা", "বালিয়াকান্দি", "কালুখালী"],
    55: ["রাজশাহী সদর", "পবা", "তানোর", "গোদাগাড়ী", "মোহনপুর", "বাগমারা", "দুর্গাপুর", "পুঠিয়া", "চারঘাট", "বাঘা"],
    56: ["লক্ষ্মীপুর সদর", "রায়পুর", "রামগঞ্জ", "রামগতি", "কমলনগর"],
    57: ["লালমনিরহাট সদর", "কালীগঞ্জ", "হাতীবান্ধা", "পাটগ্রাম", "আদিতমারী"],
    58: ["শরীয়তপুর সদর", "ডামুড্যা", "নড়িয়া", "জাজিরা", "ভেদরগঞ্জ", "গোসাইরহাট"],
    59: ["শেরপুর সদর", "নালিতাবাড়ী", "ঝিনাইগাতী", "নকলা", "শ্রীবরদী"],
    60: ["সাতক্ষীরা সদর", "কলারোয়া", "তালা", "আশাশুনি", "শ্যামনগর", "কালীগঞ্জ", "দেবহাটা"],
    61: ["সিরাজগঞ্জ সদর", "বেলকুচি", "চৌহালী", "কামারখন্দ", "কাজীপুর", "রায়গঞ্জ", "শাহজাদপুর", "তাড়াশ", "উল্লাপাড়া"],
    62: ["সিলেট সদর", "বিয়ানীবাজার", "গোলাপগঞ্জ", "ফেঞ্চুগঞ্জ", "বালাগঞ্জ", "বিশ্বনাথ", "কোম্পানীগঞ্জ", "গৌরীপুর", "জৈন্তাপুর", "কানাইঘাট", "জকিগঞ্জ", "দক্ষিণ সুরমা", "ওসমানীনগর"],
    63: ["সুনামগঞ্জ সদর", "ছাতক", "জগন্নাথপুর", "দিরাই", "শাল্লা", "ধর্মপাশা", "তাহিরপুর", "বিশ্বম্ভরপুর", "দোয়ারাবাজার", "জামালগঞ্জ", "মধ্যনগর"],
    64: ["হবিগঞ্জ সদর", "নবীগঞ্জ", "বাহুবল", "আজমিরীগঞ্জ", "বানিয়াচং", "লাখাই", "চুনারুঘাট", "মাধবপুর", "শায়েস্তাগঞ্জ"]    
}

export const upazilasEn: { [key: number]: string[] } = {
  1: ["Cox's Bazar Sadar", "Ukhiya", "Teknaf", "Ramu", "Chakaria", "Moheshkhali", "Pekua", "Kutubdia", "Eidgaon"],
  2: ["Kishoreganj Sadar", "Karimganj", "Tarail", "Hossainpur", "Kotiadi", "Kuliarchar", "Bhairab", "Nikli", "Bajitpur", "Itna", "Mithamain", "Austagram", "Pakundia"],
  3: ["Cumilla Sadar", "Laksam", "Debidwar", "Muradnagar", "Daudkandi", "Chauddagram", "Barura", "Burichang", "Brahmanpara", "Chandina", "Homna", "Laksam", "Meghna", "Monohargonj", "Titas", "Sadar South"],
  4: ["Kushtia Sadar", "Kumarkhali", "Khoksa", "Mirpur", "Daulatpur", "Bheramara"],
  5: ["Kurigram Sadar", "Ulipur", "Chilmari", "Rhumari", "Char Rajibpur", "Nageshwari", "Bhurungamari", "Rajarhat", "Kurigram Phulbari"],
  6: ["Khagrachhari Sadar", "Dighinala", "Panchhari", "Matiranga", "Mahalchhari", "Manikchhari", "Ramgarh", "Lakshmichhari", "Guimara"],
  7: ["Khulna Sadar", "Koyra", "Dumuria", "Terkhada", "Dacope", "Dighalia", "Paikgacha", "Phultala", "Batiaghata", "Rupsha"],
  8: ["Gaibandha Sadar", "Sadullapur", "Palashbari", "Sundarganj", "Saghata", "Gobindaganj", "Fulchhari"],
  9: ["Gazipur Sadar", "Kaliakair", "Kaliganj", "Kapasia", "Sreepur"],
  10: ["Gopalganj Sadar", "Kotalipara", "Tungipara", "Kashiani", "Muksudpur"],
  11: ["Chattogram Sadar", "Patiya", "Anwara", "Chandananish", "Banshkhali", "Boalkhali", "Rangunia", "Rauzan", "Hathazari", "Mirsarai", "Sitakunda", "Fatikchhari", "Sandwip", "Satkania", "Lohagara"],
  12: ["Chandpur Sadar", "Haziganj", "Kachua", "Faridganj", "Matlab North", "Matlab South", "Haimchar", "Shahrasti"],
  13: ["Chapainawabganj Sadar", "Shibganj", "Gomastapur", "Nachole", "Volahat"],
  14: ["Chuadanga Sadar", "Alamdanga", "Damurhuda", "Jibannagar"],
  15: ["Jamalpur Sadar", "Melandah", "Islampur", "Dewanganj", "Sarishabari", "Madarganj", "Bakshiganj"],
  16: ["Joypurhat Sadar", "Panchbibi", "Akkelpur", "Kalai", "Khetlal"],
  17: ["Jhalokati Sadar", "Nalchity", "Rajapur", "Kathalia"],
  18: ["Jhenaidah Sadar", "Shailkupa", "Harinakundu", "Kaliganj", "Kotchandpur", "Moheshpur"],
  19: ["Tangail Sadar", "Kalihati", "Ghatail", "Basail", "Gopalpur", "Mirzapur", "Nagarpur", "Madhupur", "Sakhipur", "Delduar", "Dhanbari", "Bhuapur"],
  20: ["Thakurgaon Sadar", "Pirganj", "Baliadangi", "Ranisankail", "Haripur"],
  
  21: ["Savar", "Ashulia", "Hemayetpur", "Nabinagar", "Dhamrai", "Keraniganj", "Kadamtali (Keraniganj)", "Zinzira", "Nawabganj", "Dohar", "Mirpur-1", "Mirpur-2", "Mirpur-10", "Mirpur-11", "Mirpur-12", "Mirpur-13", "Mirpur-14", "Mirpur DOHS", "Mirpur-60 Feet", "Sherapara", "Kazipara", "Pallabi", "Rupnagar", "Shah Ali", "Kafrul", "Agargaon", "Taltola", "Uttara Sector-1 to 10", "Uttara Sector-11 to 18", "Uttara Model Town", "Diabari", "Abdullahpur", "Uttarakhan", "Dakshinkhan", "Faidabad", "Airport Area", "Khilkhet", "Nikunja-1", "Nikunja-2", "Kuril", "Kuratoli", "Joar Sahara", "Bashundhara Residential Area", "Baridhara Residential Area", "Baridhara DOHS", "Nadda", "Kalachandpur", "Gulshan-1", "Gulshan-2", "Banani", "Banani DOHS", "Mohakhali", "Mohakhali DOHS", "Niketan", "Tejgaon", "Tejgaon Industrial Area", "Karwan Bazar", "Farmgate", "Rajabazar", "Indira Road", "Dhanmondi", "Kalabagan", "Kathalbagan", "Green Road", "Central Road", "Mohammadpur", "Japan Garden City", "Shia Masjid", "Adabor", "Shekhertek", "Dhaka Udyan", "Bosila", "Hazaribagh", "Jigatola", "Lalmatia", "Rayerbazar", "Lalbagh", "Chawkbazar", "Islampur", "Kotwali", "Babu Bazar", "Nawabpur", "Sadarghat", "Sutrapur", "Gendaria", "Wari", "Tipu Sultan Road", "Jatrabari", "Dhalpur", "Shonir Akhra", "Rayerbagh", "Matuail", "Donia", "Demra", "Shyampur", "Kadamtali", "Sabujbagh", "Basabo", "Khilgaon", "Sipahibagh", "Goran", "Rampura", "Banasree", "Aftabnagar", "Malibagh", "Mouchak", "Moghbazar", "Siddheswari", "Bailey Road", "Shantinagar", "Kakrail", "Palton", "Motijheel", "Dilkusha", "Kamalapur", "Shahjahanpur", "Mugda", "Manda", "Maniknagar", "Sayedabad", "Ramna", "Shahbagh", "Dhaka University Area", "New Market", "Azimpur", "Nilkhet", "Bakshibazar", "Segunbagicha", "Topkhana Road", "Hatirjheel", "Badda", "Uttar Badda", "South Badda", "Middle Badda", "Merul Badda", "Shahzadpur", "Vatara", "Satarkul", "Beraid", "Kamrangirchar", "Bhashantek", "Manikdi", "Matikata", "Dhaka Cantonment"],

  22: ["Dinajpur Sadar", "Birampur", "Nawabganj", "Birganj", "Bochaganj", "Chirirbandar", "Phulbari", "Kaharole", "Khansama", "Parbatipur", "Hakimpur", "Ghoraghat"],
  23: ["Naogaon Sadar", "Patnitala", "Dhamoirhat", "Mahadebpur", "Porsha", "Sapahar", "Badalgachhi", "Atrai", "Raninagar", "Niamatpur", "Manda"],
  24: ["Narsingdi Sadar", "Palash", "Shibpur", "Monohardi", "Belabo", "Raipura"],
  25: ["Natore Sadar", "Bagatipara", "Baraigram", "Gurudaspur", "Lalpur", "Singra", "Naldanga"],
  26: ["Narayanganj Sadar", "Bandar", "Araihazar", "Rupganj", "Sonargaon"],
  27: ["Nilphamari Sadar", "Sayedpur", "Jaldhaka", "Kishoreganj", "Domar", "Dimla"],
  28: ["Netrokona Sadar", "Barhatta", "Kalamakanda", "Durgapur", "Kendua", "Madan", "Mohanganj", "Purbadhala", "Khaliajuri", "Atpara"],
  29: ["Noakhali Sadar", "Companiganj", "Begumganj", "Chatkhil", "Senbagh", "Hatiya", "Subarnachar", "Sonaimuri", "Kabirhat"],
  30: ["Narail Sadar", "Lohagara", "Kalia"],

  31: ["Panchagarh Sadar", "Tetulia", "Boda", "Debiganj", "Atwari"],
  32: ["Patuakhali Sadar", "Bauphal", "Galachipa", "Dashmina", "Mirzaganj", "Kalapara", "Dumki", "Rangabali"],
  33: ["Pabna Sadar", "Ishwardi", "Bhangura", "Chatmohar", "Faridpur", "Sujanagar", "Bera", "Atgharia", "Santhia"],
  34: ["Pirojpur Sadar", "Nazirpur", "Nesarabad", "Kawkhali", "Bhandaria", "Mathbaria", "Indurkani"],
  35: ["Faridpur Sadar", "Alfadanga", "Boalmari", "Sadorpur", "Nagarkanda", "Bhanga", "Charbhadrasan", "Madhukhali", "Saltha"],
  36: ["Feni Sadar", "Chhagalnaiya", "Parshuram", "Fulgazi", "Daganbhuiyan", "Sonagazi"],
  37: ["Bogra Sadar", "Shajahanpur", "Sherpur", "Dhunat", "Nandigram", "Kahalu", "Adamdighi", "Dupchanchia", "Shibganj", "Sonatala", "Gabtoli", "Sariakandi"],
  38: ["Barguna Sadar", "Amtali", "Patharghata", "Bamna", "Betagi", "Taltali"],
  39: ["Barishal Sadar", "Bakerganj", "Babuganj", "Wazirpur", "Banaripara", "Gournadi", "Agailjhara", "Muladi", "Mehendiganj", "Hizla"],
  40: ["Bagerhat Sadar", "Fakirhat", "Mollahat", "Chitalmari", "Kachua", "Rampal", "Mongla", "Sarankhola", "Morrelganj"],
  
  41: ["Bandarban Sadar", "Ruma", "Thanchi", "Rowangchhari", "Lama", "Alikadam", "Naikhongchhari"],
  42: ["Brahmanbaria Sadar", "Kasba", "Nasirnagar", "Sarail", "Ashuganj", "Akhaura", "Nabinnagar", "Bancharampur", "Bijoynagar"],
  43: ["Bhola Sadar", "Borhanuddin", "Char Fasson", "Lalmohan", "Tazumuddin", "Daulatkhan", "Manpura"],
  44: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
  45: ["Madaripur Sadar", "Shibchar", "Kalkini", "Rajoir", "Dasar"],
  46: ["Manikganj Sadar", "Singair", "Ghior", "Saturia", "Harirampur", "Shibalaya", "Daulatpur"],
  47: ["Munshiganj Sadar", "Sreenagar", "Sirajdikhan", "Louhajang", "Tongibari", "Gajaria"],
  48: ["Meherpur Sadar", "Gangni", "Mujibnagar"],
  49: ["Moulvibazar Sadar", "Sreemangal", "Rajnagar", "Kulaura", "Barlekha", "Kamalganj", "Juri"],
  50: ["Mymensingh Sadar", "Muktagachha", "Fulbaria", "Trishal", "Bhaluka", "Gafargaon", "Ishwarganj", "Nandail", "Gauripur", "Phulpur", "Dhobaura", "Haluaghat", "Tarakanda"],
  
  51: ["Jashore Sadar", "Jhikargachha", "Sharsha", "Chougachha", "Keshabpur", "Manirampur", "Abhaynagar", "Bagherpara"],
  52: ["Rangpur Sadar", "Mithapukur", "Pirganj", "Pirgachha", "Kaunia", "Gangachhara", "Badarganj", "Tapadhan"],
  53: ["Rangamati Sadar", "Kaptai", "Kawkhali", "Baghaichhari", "Langadu", "Naniarchar", "Rajasthali", "Jurachhari", "Barkal", "Bilaichhari"],
  54: ["Rajbari Sadar", "Goalanda", "Pangsha", "Baliakandi", "Kalukhali"],
  55: ["Rajshahi Sadar", "Paba", "Tanore", "Godagari", "Mohanpur", "Bagmara", "Durgapur", "Puthia", "Charghat", "Bagha"],
  56: ["Lakshmipur Sadar", "Raipur", "Ramganj", "Ramgati", "Kamalnagar"],
  57: ["Lalmonirhat Sadar", "Kaliganj", "Hatibandha", "Patgram", "Aditmari"],
  58: ["Shariatpur Sadar", "Damudya", "Naria", "Zajira", "Bhederganj", "Gosairhat"],
  59: ["Sherpur Sadar", "Nalitabari", "Jhenaigati", "Nakla", "Sreebardi"],
  60: ["Satkhira Sadar", "Kalaroa", "Tala", "Ashashuni", "Shyamnagar", "Kaliganj", "Debhata"],
  61: ["Sirajganj Sadar", "Belkuchi", "Chauhali", "Kamarkhanda", "Kazipur", "Rayganj", "Shahzadpur", "Tarash", "Ullapara"],
  62: ["Sylhet Sadar", "Beanibazar", "Golapganj", "Fenchuganj", "Balaganj", "Biswanath", "Companiganj", "Gauripur", "Jaintiapur", "Kanaighat", "Zakiganj", "South Surma", "Osmaninagar"],
  63: ["Sunamganj Sadar", "Chhatak", "Jagannathpur", "Derai", "Shalla", "Dharampasha", "Tahirpur", "Bishwamavpur", "Dowarabazar", "Jamalganj", "Jagannathpur"],
  64: ["Habiganj Sadar", "Nabiganj", "Bahubal", "Azmiriganj", "Baniachachong", "Lakhai", "Chunarughat", "Madhabpur", "Shayestaganj"]
};